export type MBTIType =
  | ''
  | 'INTJ'
  | 'INTP'
  | 'ENTJ'
  | 'ENTP'
  | 'INFJ'
  | 'INFP'
  | 'ENFJ'
  | 'ENFP'
  | 'ISTJ'
  | 'ISFJ'
  | 'ESTJ'
  | 'ESFJ'
  | 'ISTP'
  | 'ISFP'
  | 'ESTP'
  | 'ESFP';

export const MBTI_TYPES: MBTIType[] = [
  'INTJ',
  'INTP',
  'ENTJ',
  'ENTP',
  'INFJ',
  'INFP',
  'ENFJ',
  'ENFP',
  'ISTJ',
  'ISFJ',
  'ESTJ',
  'ESFJ',
  'ISTP',
  'ISFP',
  'ESTP',
  'ESFP',
];

export type EpisodeParticipant = {
  /** 'group' reserved for future group-name tags; UI currently writes individuals only. */
  kind: 'individual' | 'group';
  value: string;
};

/** エピソードの公開範囲（参加者とは別に保持） */
export type EpisodeVisibilityEntry = {
  kind: 'individual' | 'group';
  value: string;
};

export type EpisodeVisibilityMode = 'public' | 'limited' | 'private';

export type Episode = {
  id: string;
  title: string;
  date: string;
  /** 出来事の時刻（HH:mm）。任意。未設定時は省略または null */
  time?: string | null;
  description: string;
  authorFriendId: string;
  visibilityMode: EpisodeVisibilityMode;
  participantEntries: EpisodeParticipant[];
  visibilityEntries: EpisodeVisibilityEntry[];
  /** 紐づくカレンダー予定（events.id）。未設定時は null または省略 */
  eventId?: string | null;
  /** 予定からの自動生成エピソードか（未設定時は false） */
  isAutoGenerated?: boolean;
  /** 自動生成後の確認待ちか（未設定時は false） */
  pendingReview?: boolean;
  /** 確認ポップで「後で」を選んだか。true のときは再表示しない */
  pendingReviewDismissed?: boolean;
  /** エピソード分類タグ（予定とは独立。初期値のみ予定からコピー可） */
  tag?: string | null;
};

export type Event = {
  id: string;
  title: string;
  startAt: string;
  endAt: string | null;
  allDay: boolean;
  memo: string | null;
  notifyAt: string | null;
  notifyEnabled: boolean;
  notificationId: string | null;
  autoEpisodeCreated: boolean;
  /** 予定用の分類タグ（エピソードとは独立。カレンダー色などに使用） */
  episodeTag: string | null;
  /** Google カレンダー（FriendDex 専用）上のイベント ID。未同期時は null */
  googleEventId: string | null;
  createdAt: string;
  updatedAt: string;
};

export type PendingReviewEpisodeRef = {
  profileId: string;
  friendId: string;
  friendName: string;
  episode: Episode;
};

export type EventInput = Omit<
  Event,
  'id' | 'createdAt' | 'updatedAt' | 'notificationId' | 'autoEpisodeCreated' | 'googleEventId'
> & {
  autoEpisodeCreated?: boolean;
};

export type EventParticipant = {
  eventId: string;
  profileId: string;
  createdAt: string;
};

export type EpisodePhoto = {
  id: number;
  episodeId: string;
  photoUri: string;
  sortOrder: number;
  createdAt: string;
};

export type Saying = {
  id: string;
  text: string;
  date: string;
};

export type MoneyLoanDirection = 'lent' | 'borrowed';

export type MoneyLoanCounterpartyKind = 'friend' | 'free_text';

export type MoneyLoanCounterparty = {
  kind: MoneyLoanCounterpartyKind;
  value: string;
};

export type MoneyLoanSession = {
  id: string;
  title: string;
  createdAt: string;
};

export type MoneyLoan = {
  id: string;
  sessionId: string;
  groupId: string;
  counterpartyKind: MoneyLoanCounterpartyKind;
  counterpartyValue: string;
  amount: number;
  direction: MoneyLoanDirection;
  memo: string;
  isRepaid: boolean;
  createdAt: string;
};

export type CreateMoneyLoanLineInput = {
  kind: MoneyLoanCounterpartyKind;
  value: string;
  amount: number;
  direction: MoneyLoanDirection;
};

export type CreateMoneyLoansInput = {
  sessionId: string;
  lines: CreateMoneyLoanLineInput[];
  memo?: string;
};

export type ShufflePool = {
  id: string;
  label: string;
  labelIsCustom: boolean;
  memberIds: string[];
  createdAt: string;
  lastUsedAt: string;
};

export type ImportSource = 'manual' | 'qr_scan';

export type Profile = {
  id: string;
  friendId: string;
  /** 表示名（苗字＋半角スペース＋名前。同一 friendId の全プロフィールで共通） */
  name: string;
  familyName: string;
  givenName: string;
  authorUserId: string | null;
  source: 'self' | 'shared';
  isDefault: boolean;
  nickname: string;
  origin: string;
  residence: string;
  mbti: MBTIType;
  birthday: string;
  height: number | null;
  weight: number | null;
  category: string;
  description: string;
  photoUri: string | null;
  affiliations: string[];
  personalities: string[];
  experiences: string[];
  traits: string[];
  likes: string[];
  dislikes: string[];
  episodes: Episode[];
  sayings: Saying[];
  createdAt: string;
  /** ver001では空文字。ver002でサーバー採番 */
  userId: string;
  /** 公開する項目のキー一覧 */
  publicFields: string[];
  importSource: ImportSource;
  scannedUserId: string;
  scannedAt: string;
  updatedAt: string;
};

export type Friend = {
  id: string;
  name: string;
  familyName: string;
  givenName: string;
  nickname: string;
  origin: string;
  residence: string;
  mbti: MBTIType;
  birthday: string;
  height: number | null;
  weight: number | null;
  category: string;
  description: string;
  photoUri: string | null;
  affiliations: string[];
  personalities: string[];
  experiences: string[];
  traits: string[];
  likes: string[];
  dislikes: string[];
  episodes: Episode[];
  sayings: Saying[];
  profiles?: Profile[];
  activeProfileId?: string;
  importSource: ImportSource;
  scannedUserId: string;
  scannedAt: string;
};

export type FriendInput = Omit<
  Friend,
  'id' | 'episodes' | 'sayings' | 'importSource' | 'scannedUserId' | 'scannedAt'
> & {
  episodes?: Episode[];
  sayings?: Saying[];
};

export type FriendSearchFilters = {
  name?: string;
  affiliation1?: string;
  affiliation2?: string;
  birthMonth?: number;
  mbti?: MBTIType;
  experience?: string;
};

export type CommonItemKind =
  | 'affiliation'
  | 'experience'
  | 'personality'
  | 'like'
  | 'dislike'
  | 'visibility_group'
  | 'episode_tag';

export type CommonItemOption = {
  id: string;
  kind: CommonItemKind;
  label: string;
  members: string[];
  /** 予定タグ用。カレンダー帯色（#RRGGBB）。他 kind は null */
  color: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TaskKind = 'recurring' | 'temporary';
export type TaskPace = 'scheduled' | 'unpaced';
export type TaskRecurrenceUnit = 'day' | 'week' | 'month' | 'year';

export type TaskRecurrenceConfig = {
  weekdays?: number[];
  weekStartsOn?: number;
  monthDay?: number;
  /** @deprecated use monthNths */
  monthNth?: number;
  /** @deprecated use monthWeekdays */
  monthWeekday?: number;
  monthNths?: number[];
  monthWeekdays?: number[];
  yearMonth?: number;
  yearDay?: number;
};

export type Task = {
  id: string;
  kind: TaskKind;
  title: string;
  memo: string;
  pace: TaskPace | null;
  recurrenceUnit: TaskRecurrenceUnit | null;
  recurrenceConfig: TaskRecurrenceConfig | null;
  dueDate: string | null;
  eventId: string | null;
  /** 所属グループ（定期グループ / 臨時グループ。kind はタスクと一致） */
  groupId: string | null;
  /**
   * 実施履歴・連続・ドットを残すか（定期）。デフォルト true。
   * false の日次チェックはソフト完了のみ（履歴に残さない）。
   */
  trackCompletions: boolean;
  completedAt: string | null;
  /** リマインド（初期OFF）。グループ内の定期はグループ設定を使う */
  remindEnabled: boolean;
  /** 臨時のみ。0=期限当日、1〜30=何日前 */
  remindDaysBefore: number | null;
  /** `HH:mm` ローカル時刻 */
  remindTime: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TaskInput = {
  kind: TaskKind;
  title: string;
  memo?: string;
  pace?: TaskPace | null;
  recurrenceUnit?: TaskRecurrenceUnit | null;
  recurrenceConfig?: TaskRecurrenceConfig | null;
  dueDate?: string | null;
  eventId?: string | null;
  groupId?: string | null;
  trackCompletions?: boolean;
  remindEnabled?: boolean;
  remindDaysBefore?: number | null;
  remindTime?: string | null;
};

/** 1グループに入れられるタスクの上限（定期・臨時とも） */
export const TASK_GROUP_MEMBER_LIMIT = 10;

export type TaskGroup = {
  id: string;
  /** 定期グループ / 臨時グループ（混在不可） */
  kind: TaskKind;
  title: string;
  /**
   * 定期グループの追加周期（メンバー必須の OR 用）。
   * null / unpaced = グループ固有の必須日なし。臨時は常に null。
   */
  pace: TaskPace | null;
  recurrenceUnit: TaskRecurrenceUnit | null;
  recurrenceConfig: TaskRecurrenceConfig | null;
  sortOrder: number;
  /** 定期グループのみ。要対応日の時刻リマインド */
  remindEnabled: boolean;
  remindTime: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TaskGroupInput = {
  title: string;
  kind: TaskKind;
  pace?: TaskPace | null;
  recurrenceUnit?: TaskRecurrenceUnit | null;
  recurrenceConfig?: TaskRecurrenceConfig | null;
  sortOrder?: number;
  remindEnabled?: boolean;
  remindTime?: string | null;
};

export type TaskCompletion = {
  id: string;
  taskId: string;
  completedOn: string;
  createdAt: string;
};

export type CompletedTaskRetention = '1w' | '1m' | '3m' | '1y' | 'forever';

/** 相関図そのもの */
export type RelationshipMap = {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
};

export type RelationshipMapInput = {
  title: string;
};

/** 相関図上の人物ノード（グリッド座標） */
export type RelationshipMapMember = {
  id: string;
  mapId: string;
  friendId: string;
  row: number;
  col: number;
};

export type RelationshipMapMemberInput = {
  mapId: string;
  friendId: string;
  row: number;
  col: number;
};

/** 相関図のグループ（入れ子可。末端グループのみ人物が直接所属） */
export type RelationshipGroup = {
  id: string;
  mapId: string;
  name: string;
  color: string;
  parentGroupId: string | null;
};

export type RelationshipGroupInput = {
  mapId: string;
  name: string;
  color: string;
  parentGroupId?: string | null;
};

export type RelationshipGroupMember = {
  id: string;
  groupId: string;
  mapMemberId: string;
};

export type RelationshipEndpointType = 'person' | 'group';

export type RelationshipArrowStyle = 'oneway' | 'both' | 'none';

/** 人物間 or グループ間の関係（矢印） */
export type Relationship = {
  id: string;
  mapId: string;
  fromType: RelationshipEndpointType;
  fromId: string;
  toType: RelationshipEndpointType;
  toId: string;
  label: string | null;
  style: RelationshipArrowStyle;
};

/** 「あなたの～は？」の質問 */
export type YourQuestion = {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
};

export type YourQuestionInput = {
  title: string;
};

/** 1質問 × 1人物の回答 */
export type YourQuestionAnswer = {
  id: string;
  questionId: string;
  friendId: string;
  body: string;
  createdAt: string;
  updatedAt: string;
};

export type YourQuestionAnswerInput = {
  questionId: string;
  friendId: string;
  body: string;
};

/** 行ってみたい・食べてみたい */
export type WishlistKind = 'visit' | 'eat';

export type WishlistItem = {
  id: string;
  kind: WishlistKind;
  name: string;
  purposeTags: string[];
  location: string | null;
  cuisine: string | null;
  memo: string | null;
  link: string | null;
  createdAt: string;
  updatedAt: string;
};

export type WishlistItemInput = {
  kind: WishlistKind;
  name: string;
  purposeTags?: string[];
  location?: string | null;
  cuisine?: string | null;
  memo?: string | null;
  link?: string | null;
};

export type RelationshipInput = {
  mapId: string;
  fromType: RelationshipEndpointType;
  fromId: string;
  toType: RelationshipEndpointType;
  toId: string;
  label?: string | null;
  style: RelationshipArrowStyle;
};

export const FRIENDDEX_BACKUP_V1_TABLE_NAMES = [
  'friend_profiles',
  'app_settings',
  'common_item_options',
] as const;

/** v3 / v4 までのテーブル（予定まで） */
export const FRIENDDEX_BACKUP_V4_TABLE_NAMES = [
  ...FRIENDDEX_BACKUP_V1_TABLE_NAMES,
  'episode_photos',
  'events',
  'event_participants',
] as const;

/** v5: タスク・お金・精算・シャッフル */
export const FRIENDDEX_BACKUP_V5_TABLE_NAMES = [
  ...FRIENDDEX_BACKUP_V4_TABLE_NAMES,
  'task_groups',
  'tasks',
  'task_completions',
  'task_soft_dones',
  'money_loan_sessions',
  'money_loans',
  'settlement_rooms',
  'settlement_members',
  'settlement_expenses',
  'settlement_transfer_completions',
  'shuffle_pools',
] as const;

/** v6: 相関図 */
export const FRIENDDEX_BACKUP_V6_TABLE_NAMES = [
  ...FRIENDDEX_BACKUP_V5_TABLE_NAMES,
  'relationship_maps',
  'relationship_map_members',
  'relationship_groups',
  'relationship_group_members',
  'relationships',
] as const;

/** v7: あなたの～は？ */
export const FRIENDDEX_BACKUP_V7_TABLE_NAMES = [
  ...FRIENDDEX_BACKUP_V6_TABLE_NAMES,
  'your_questions',
  'your_question_answers',
] as const;

/** 現行バックアップ対象（v8: 行ってみたい・食べてみたい） */
export const FRIENDDEX_BACKUP_TABLE_NAMES = [
  ...FRIENDDEX_BACKUP_V7_TABLE_NAMES,
  'wishlist_items',
] as const;

export type FriendDexBackupTableName = (typeof FRIENDDEX_BACKUP_TABLE_NAMES)[number];

export type FriendDexBackupRow = Record<string, string | number | null>;

export type FriendDexBackup = {
  version: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  exportedAt: string;
  tables: Record<(typeof FRIENDDEX_BACKUP_V1_TABLE_NAMES)[number], FriendDexBackupRow[]> & {
    episode_photos?: FriendDexBackupRow[];
    events?: FriendDexBackupRow[];
    event_participants?: FriendDexBackupRow[];
    task_groups?: FriendDexBackupRow[];
    tasks?: FriendDexBackupRow[];
    task_completions?: FriendDexBackupRow[];
    task_soft_dones?: FriendDexBackupRow[];
    money_loan_sessions?: FriendDexBackupRow[];
    money_loans?: FriendDexBackupRow[];
    settlement_rooms?: FriendDexBackupRow[];
    settlement_members?: FriendDexBackupRow[];
    settlement_expenses?: FriendDexBackupRow[];
    settlement_transfer_completions?: FriendDexBackupRow[];
    shuffle_pools?: FriendDexBackupRow[];
    relationship_maps?: FriendDexBackupRow[];
    relationship_map_members?: FriendDexBackupRow[];
    relationship_groups?: FriendDexBackupRow[];
    relationship_group_members?: FriendDexBackupRow[];
    relationships?: FriendDexBackupRow[];
    your_questions?: FriendDexBackupRow[];
    your_question_answers?: FriendDexBackupRow[];
    wishlist_items?: FriendDexBackupRow[];
  };
};

