export type MBTIType =
  | ''
  | 'INTJ'
  | 'INTP'
  | 'ENTJ'
  | 'ENTP'
  | 'INFJ'
  | 'INFP'
  | 'ENFJ'
  | 'ENFP'
  | 'ISTJ'
  | 'ISFJ'
  | 'ESTJ'
  | 'ESFJ'
  | 'ISTP'
  | 'ISFP'
  | 'ESTP'
  | 'ESFP';

export const MBTI_TYPES: MBTIType[] = [
  'INTJ',
  'INTP',
  'ENTJ',
  'ENTP',
  'INFJ',
  'INFP',
  'ENFJ',
  'ENFP',
  'ISTJ',
  'ISFJ',
  'ESTJ',
  'ESFJ',
  'ISTP',
  'ISFP',
  'ESTP',
  'ESFP',
];

export type EpisodeParticipant = {
  kind: 'individual' | 'group';
  value: string;
};

/** エピソードの公開範囲（参加者とは別に保持） */
export type EpisodeVisibilityEntry = {
  kind: 'individual' | 'group';
  value: string;
};

export type EpisodeVisibilityMode = 'public' | 'limited' | 'private';

export type Episode = {
  id: string;
  title: string;
  date: string;
  description: string;
  authorFriendId: string;
  visibilityMode: EpisodeVisibilityMode;
  participantEntries: EpisodeParticipant[];
  visibilityEntries: EpisodeVisibilityEntry[];
  /** 紐づくカレンダー予定（events.id）。未設定時は null または省略 */
  eventId?: string | null;
  /** 予定からの自動生成エピソードか（未設定時は false） */
  isAutoGenerated?: boolean;
  /** 自動生成後の確認待ちか（未設定時は false） */
  pendingReview?: boolean;
  /** エピソード分類タグ（予定とは独立。初期値のみ予定からコピー可） */
  tag?: string | null;
};

export type Event = {
  id: string;
  title: string;
  startAt: string;
  endAt: string | null;
  allDay: boolean;
  memo: string | null;
  notifyAt: string | null;
  notifyEnabled: boolean;
  notificationId: string | null;
  autoEpisodeCreated: boolean;
  /** 予定用の分類タグ（エピソードとは独立。カレンダー色などに使用） */
  episodeTag: string | null;
  createdAt: string;
  updatedAt: string;
};

export type PendingReviewEpisodeRef = {
  profileId: string;
  friendId: string;
  friendName: string;
  episode: Episode;
};

export type EventInput = Omit<
  Event,
  'id' | 'createdAt' | 'updatedAt' | 'notificationId' | 'autoEpisodeCreated'
> & {
  autoEpisodeCreated?: boolean;
};

export type EventParticipant = {
  eventId: string;
  profileId: string;
  createdAt: string;
};

export type EpisodePhoto = {
  id: number;
  episodeId: string;
  photoUri: string;
  sortOrder: number;
  createdAt: string;
};

export type Saying = {
  id: string;
  text: string;
  date: string;
};

export type MoneyLoanDirection = 'lent' | 'borrowed';

export type MoneyLoanCounterpartyKind = 'friend' | 'free_text';

export type MoneyLoanCounterparty = {
  kind: MoneyLoanCounterpartyKind;
  value: string;
};

export type MoneyLoanSession = {
  id: string;
  title: string;
  createdAt: string;
};

export type MoneyLoan = {
  id: string;
  sessionId: string;
  groupId: string;
  counterpartyKind: MoneyLoanCounterpartyKind;
  counterpartyValue: string;
  amount: number;
  direction: MoneyLoanDirection;
  memo: string;
  isRepaid: boolean;
  createdAt: string;
};

export type CreateMoneyLoanLineInput = {
  kind: MoneyLoanCounterpartyKind;
  value: string;
  amount: number;
  direction: MoneyLoanDirection;
};

export type CreateMoneyLoansInput = {
  sessionId: string;
  lines: CreateMoneyLoanLineInput[];
  memo?: string;
};

export type ShufflePool = {
  id: string;
  label: string;
  labelIsCustom: boolean;
  memberIds: string[];
  createdAt: string;
  lastUsedAt: string;
};

export type ImportSource = 'manual' | 'qr_scan';

export type Profile = {
  id: string;
  friendId: string;
  /** 人物名（同一 friendId の全プロフィールで共通） */
  name: string;
  authorUserId: string | null;
  source: 'self' | 'shared';
  isDefault: boolean;
  nickname: string;
  origin: string;
  residence: string;
  mbti: MBTIType;
  birthday: string;
  height: number | null;
  weight: number | null;
  category: string;
  description: string;
  photoUri: string | null;
  affiliations: string[];
  personalities: string[];
  experiences: string[];
  traits: string[];
  likes: string[];
  dislikes: string[];
  episodes: Episode[];
  sayings: Saying[];
  createdAt: string;
  /** ver001では空文字。ver002でサーバー採番 */
  userId: string;
  /** 公開する項目のキー一覧 */
  publicFields: string[];
  importSource: ImportSource;
  scannedUserId: string;
  scannedAt: string;
  updatedAt: string;
};

export type Friend = {
  id: string;
  name: string;
  nickname: string;
  origin: string;
  residence: string;
  mbti: MBTIType;
  birthday: string;
  height: number | null;
  weight: number | null;
  category: string;
  description: string;
  photoUri: string | null;
  affiliations: string[];
  personalities: string[];
  experiences: string[];
  traits: string[];
  likes: string[];
  dislikes: string[];
  episodes: Episode[];
  sayings: Saying[];
  profiles?: Profile[];
  activeProfileId?: string;
  importSource: ImportSource;
  scannedUserId: string;
  scannedAt: string;
};

export type FriendInput = Omit<
  Friend,
  'id' | 'episodes' | 'sayings' | 'importSource' | 'scannedUserId' | 'scannedAt'
> & {
  episodes?: Episode[];
  sayings?: Saying[];
};

export type FriendSearchFilters = {
  name?: string;
  affiliation1?: string;
  affiliation2?: string;
  birthMonth?: number;
  mbti?: MBTIType;
  experience?: string;
};

export type CommonItemKind =
  | 'affiliation'
  | 'experience'
  | 'personality'
  | 'like'
  | 'dislike'
  | 'visibility_group'
  | 'episode_tag';

export type CommonItemOption = {
  id: string;
  kind: CommonItemKind;
  label: string;
  members: string[];
  /** エピソードタグ用。カレンダー帯色（#RRGGBB）。他 kind は null */
  color: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TaskKind = 'recurring' | 'temporary';
export type TaskPace = 'scheduled' | 'unpaced';
export type TaskRecurrenceUnit = 'day' | 'week' | 'month' | 'year';

export type TaskRecurrenceConfig = {
  weekdays?: number[];
  weekStartsOn?: number;
  monthDay?: number;
  /** @deprecated use monthNths */
  monthNth?: number;
  /** @deprecated use monthWeekdays */
  monthWeekday?: number;
  monthNths?: number[];
  monthWeekdays?: number[];
  yearMonth?: number;
  yearDay?: number;
};

export type Task = {
  id: string;
  kind: TaskKind;
  title: string;
  memo: string;
  pace: TaskPace | null;
  recurrenceUnit: TaskRecurrenceUnit | null;
  recurrenceConfig: TaskRecurrenceConfig | null;
  dueDate: string | null;
  eventId: string | null;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TaskInput = {
  kind: TaskKind;
  title: string;
  memo?: string;
  pace?: TaskPace | null;
  recurrenceUnit?: TaskRecurrenceUnit | null;
  recurrenceConfig?: TaskRecurrenceConfig | null;
  dueDate?: string | null;
  eventId?: string | null;
};

export type TaskCompletion = {
  id: string;
  taskId: string;
  completedOn: string;
  createdAt: string;
};

export type CompletedTaskRetention = '1w' | '1m' | '3m' | '1y' | 'forever';

export const FRIENDDEX_BACKUP_V1_TABLE_NAMES = [
  'friend_profiles',
  'app_settings',
  'common_item_options',
] as const;

export const FRIENDDEX_BACKUP_TABLE_NAMES = [
  ...FRIENDDEX_BACKUP_V1_TABLE_NAMES,
  'episode_photos',
  'events',
  'event_participants',
] as const;

export type FriendDexBackupTableName = (typeof FRIENDDEX_BACKUP_TABLE_NAMES)[number];

export type FriendDexBackupRow = Record<string, string | number | null>;

export type FriendDexBackup = {
  version: 1 | 2 | 3 | 4;
  exportedAt: string;
  tables: Record<(typeof FRIENDDEX_BACKUP_V1_TABLE_NAMES)[number], FriendDexBackupRow[]> & {
    episode_photos?: FriendDexBackupRow[];
    events?: FriendDexBackupRow[];
    event_participants?: FriendDexBackupRow[];
  };
};

