import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  Dimensions,
  Image,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { popCurrentTabScreen } from '@/utils/tabNavigation';
import { readUsableEpisodeDraft } from '@/utils/episodeDraft';
import { Ionicons } from '@expo/vector-icons';
import { Theme, Radius, Typography, Spacing } from '@/constants/theme';
import { EpisodeListCard, episodeDetailTopBarButtonStyles } from '@/components/episode/EpisodeListCard';
import { EPISODE_DETAIL_SIDE_INSET } from '@/components/episode/EpisodeCardTitle';
import { EpisodeByline } from '@/components/episode/EpisodeByline';
import { EpisodeFormOverlay } from '@/components/episode/EpisodeFormOverlay';
import type { Option } from '@/components/episode/types';
import { SubToolScreenTemplate } from '@/components/screen-templates';
import { PanelSection, SectionDivider } from '@/components/ui/Panel';
import { NoteBlockView } from '@/components/ui/NoteBlockView';
import { useUiKit } from '@/contexts/UiPreviewContext';
import { useAppThemeOptional } from '@/contexts/AppThemeContext';
import {
  contentMutedTextStyle,
  contentTextStyle,
} from '@/utils/contentStyleHelpers';
import { useContentColors } from '@/utils/useContentColors';
import { useEpisodeForm } from '@/hooks/useEpisodeForm';
import { useBottomNavScrollClearance } from '@/hooks/useBottomNavScrollClearance';

import {
  deleteEpisode,
  getDistinctAffiliations,
  getDistinctExperiences,
  getEpisodeById,
  getEpisodePhotos,
  getEvent,
  getIncomingSharedEpisodePhotos,
  getIncomingSharedEpisodeRecord,
  markIncomingSharedEpisodeSeen,
  getMergedEpisodeTagLabels,
  getMyself,
  incomingSharedRecordToEpisode,
  initializeDatabase,
  parseIncomingSharedEpisodeId,
  updateEpisode,
  type EpisodeInput,
} from '../db';
import { scheduleOwnedEpisodeDelete, scheduleOwnedEpisodeSync } from '@/lib/ownedEpisodeSync';
import { afterEpisodeSavedLocally, guardEpisodeShareOnline } from '@/lib/episodeShareSave';
import { republishSharedEpisodeIfPublished } from '@/lib/sharedEpisodeSync';
import { Episode, EpisodePhoto, Event, Friend } from '../types';
import {
  buildParticipantChips,
  canManageEpisode,
  formatEpisodeDateTimeForDetail,
  resolveEpisodeRecordOwnerId,
  visibilityDisplayLabels,
} from '../utils/episodeHelpers';
import {
  EVENT_CREATE_FAILED_MESSAGE,
  resolveEpisodeSaveEventId,
} from '../utils/episodeEventLinking';
import { registerSavedEpisodeTag } from '../utils/episodeTagMaster';
import { getAllFriendsInDefaultOrder } from '@/utils/friendDefaultSort';
import { buildFriendPhotoById } from '@/utils/friendPhoto';
import { noteBlocksHaveContent } from '@/utils/noteBlocks';

const LIST_HORIZONTAL_INSET = 12;
const PHOTO_GAP = 6;
/** 2枚以上のとき、右端に次の写真を覗かせる幅 */
const PHOTO_PEEK = 28;

function episodeToInput(episode: Episode, description: string): EpisodeInput {
  return {
    title: episode.title,
    date: episode.date,
    time: episode.time,
    description,
    visibilityMode: episode.visibilityMode,
    participantEntries: episode.participantEntries,
    visibilityEntries: episode.visibilityEntries,
    eventId: episode.eventId,
    isAutoGenerated: episode.isAutoGenerated,
    pendingReview: episode.pendingReview,
    pendingReviewDismissed: episode.pendingReviewDismissed,
    tag: episode.tag,
    locationTag: null,
  };
}

export default function EpisodeDetailScreen() {
  const router = useRouter();
  const kit = useUiKit();
  const appTheme = useAppThemeOptional();
  const content = useContentColors();
  const bottomNavClearance = useBottomNavScrollClearance();
  const editButtonBorderColor =
    appTheme?.colors.topBarBorder ?? Theme.topBarBorder;
  const params = useLocalSearchParams<{ episodeId?: string; ownerId?: string; edit?: string }>();
  const [episode, setEpisode] = useState<Episode | null>(null);
  const [parentEvent, setParentEvent] = useState<Event | null>(null);
  const [photos, setPhotos] = useState<EpisodePhoto[]>([]);
  const [myselfId, setMyselfId] = useState<string | null>(null);
  const [friendNameById, setFriendNameById] = useState<Map<string, string>>(new Map());
  const [friendPhotoById, setFriendPhotoById] = useState<Map<string, string | null>>(new Map());
  const [lightboxPhoto, setLightboxPhoto] = useState<string | null>(null);
  const [friends, setFriends] = useState<Friend[]>([]);
  const [affiliationOptions, setAffiliationOptions] = useState<Option[]>([]);
  const [experienceOptions, setExperienceOptions] = useState<Option[]>([]);
  const [episodeTagOptions, setEpisodeTagOptions] = useState<Option[]>([]);
  const [isEditVisible, setIsEditVisible] = useState(false);
  const episodeSaveLockRef = useRef(false);
  const [episodeSaving, setEpisodeSaving] = useState(false);
  const openedEditFromParamRef = useRef(false);

  const hiddenParticipantIds = useMemo(() => (myselfId ? [myselfId] : []), [myselfId]);
  const episodeForm = useEpisodeForm({ friends, hiddenParticipantIds });
  const sectionDividerStyle = useMemo(
    () => ({
      height: 1,
      backgroundColor: content.contentDivider,
    }),
    [content.contentDivider]
  );

  const episodeId = useMemo(() => {
    if (Array.isArray(params.episodeId)) return params.episodeId[0] ?? '';
    return params.episodeId ?? '';
  }, [params.episodeId]);

  const ownerId = useMemo(() => {
    if (Array.isArray(params.ownerId)) return params.ownerId[0] ?? '';
    return params.ownerId ?? '';
  }, [params.ownerId]);

  const shouldOpenEdit = useMemo(() => {
    const raw = Array.isArray(params.edit) ? params.edit[0] : params.edit;
    return raw === '1' || raw === 'true';
  }, [params.edit]);

  const photoContentWidth = useMemo(() => {
    const panelWidth = Dimensions.get('window').width;
    return Math.max(0, panelWidth - Spacing.md * 2);
  }, []);

  const loadData = useCallback(() => {
    initializeDatabase();
    setMyselfId(getMyself());
    const allFriends = getAllFriendsInDefaultOrder();
    setFriends(allFriends);
    setFriendNameById(new Map(allFriends.map((f) => [f.id, f.name])));
    setFriendPhotoById(buildFriendPhotoById(allFriends));
    setAffiliationOptions(getDistinctAffiliations().map((v) => ({ label: v, value: v })));
    setExperienceOptions(getDistinctExperiences().map((v) => ({ label: v, value: v })));
    setEpisodeTagOptions(getMergedEpisodeTagLabels().map((v) => ({ label: v, value: v })));

    if (!episodeId || !ownerId) {
      setEpisode(null);
      setParentEvent(null);
      setPhotos([]);
      return;
    }

    const incomingId = parseIncomingSharedEpisodeId(episodeId);
    if (incomingId) {
      const incoming = getIncomingSharedEpisodeRecord(incomingId);
      if (incoming) {
        markIncomingSharedEpisodeSeen(incomingId);
      }
      setEpisode(incoming ? incomingSharedRecordToEpisode(incoming) : null);
      setParentEvent(null);
      setPhotos(incoming ? getIncomingSharedEpisodePhotos(incomingId) : []);
      return;
    }

    const loaded = getEpisodeById(ownerId, episodeId);
    setEpisode(loaded);
    const linkedEventId = loaded?.eventId?.trim();
    setParentEvent(linkedEventId ? getEvent(linkedEventId) : null);
    setPhotos(getEpisodePhotos(episodeId));
  }, [episodeId, ownerId]);

  useFocusEffect(
    useCallback(() => {
      loadData();
    }, [loadData])
  );

  const episodeForDraftRef = useRef(episode);
  episodeForDraftRef.current = episode;
  const isEditVisibleRef = useRef(isEditVisible);
  isEditVisibleRef.current = isEditVisible;
  const shouldOpenEditRef = useRef(shouldOpenEdit);
  shouldOpenEditRef.current = shouldOpenEdit;
  const editDraftPromptLockRef = useRef(false);
  useFocusEffect(
    useCallback(() => {
      const current = episodeForDraftRef.current;
      if (
        !current ||
        current.id !== episodeId ||
        isEditVisibleRef.current ||
        editDraftPromptLockRef.current
      ) {
        return;
      }
      const draft = readUsableEpisodeDraft(current.id, current.description);
      if (!draft) {
        return;
      }
      editDraftPromptLockRef.current = true;
      if (shouldOpenEditRef.current) {
        router.setParams({ edit: undefined });
      }
      const finishPrompt = () => {
        editDraftPromptLockRef.current = false;
      };
      Alert.alert('前回の下書きを復元しますか？', undefined, [
        {
          text: '復元しない',
          style: 'cancel',
          onPress: () => {
            finishPrompt();
            episodeForm.declineDraft(draft);
          },
        },
        {
          text: '復元する',
          onPress: () => {
            finishPrompt();
            const latest = episodeForDraftRef.current;
            if (!latest || latest.id !== current.id) {
              return;
            }
            episodeSaveLockRef.current = false;
            setEpisodeSaving(false);
            episodeForm.armRestoredEditDraft(latest, draft);
            setIsEditVisible(true);
          },
        },
      ]);
      return () => {
        editDraftPromptLockRef.current = false;
      };
    }, [
      episode?.description,
      episode?.id,
      episodeForm.armRestoredEditDraft,
      episodeForm.declineDraft,
      episodeId,
      router,
    ])
  );

  useEffect(() => {
    openedEditFromParamRef.current = false;
  }, [episodeId]);

  useEffect(() => {
    if (!episode || !shouldOpenEdit || openedEditFromParamRef.current) {
      return;
    }
    if (readUsableEpisodeDraft(episode.id, episode.description)) {
      return;
    }
    openedEditFromParamRef.current = true;
    episodeForm.loadFromEpisode(episode);
    setIsEditVisible(true);
    router.setParams({ edit: undefined });
  }, [episode, episodeForm.loadFromEpisode, router, shouldOpenEdit]);

  const chips = useMemo(
    () =>
      episode
        ? buildParticipantChips(episode, friendNameById, {
            excludeFriendIds: myselfId ? [myselfId] : [],
            friendPhotoById,
          })
        : [],
    [episode, friendNameById, friendPhotoById, myselfId]
  );
  const visibility = useMemo(
    () => (episode ? visibilityDisplayLabels(episode, friendNameById) : []),
    [episode, friendNameById]
  );
  const isIncomingShared = Boolean(parseIncomingSharedEpisodeId(episodeId));
  const canManage =
    episode && ownerId && !isIncomingShared
      ? canManageEpisode(episode, ownerId, myselfId)
      : false;
  const recordOwnerId = episode ? resolveEpisodeRecordOwnerId(episode, ownerId) : ownerId;
  const photoFrameWidth = useMemo(
    () => (photos.length > 1 ? Math.max(0, photoContentWidth - PHOTO_PEEK) : photoContentWidth),
    [photoContentWidth, photos.length]
  );
  const photoFrameHeight = useMemo(() => (photoFrameWidth * 3) / 4, [photoFrameWidth]);
  const hasDescription = Boolean(episode && noteBlocksHaveContent(episode.description));
  const hasPhotos = photos.length > 0;

  const renderPhotoFrame = (photo: EpisodePhoto, index: number) => (
    <Pressable
      key={photo.id}
      style={[
        styles.photoFrame,
        index > 0 ? styles.photoFrameSpaced : null,
        {
          width: photoFrameWidth,
          height: photoFrameHeight,
        },
      ]}
      onPress={() => setLightboxPhoto(photo.photoUri)}
    >
      <Image source={{ uri: photo.photoUri }} style={styles.photoImage} resizeMode="cover" />
    </Pressable>
  );

  const handleBack = useCallback(() => {
    popCurrentTabScreen();
  }, []);

  const loadFromEpisode = episodeForm.loadFromEpisode;
  const resetEpisodeForm = episodeForm.reset;

  const releaseEpisodeSaveLock = useCallback(() => {
    episodeSaveLockRef.current = false;
    setEpisodeSaving(false);
  }, []);

  const handleEdit = useCallback(() => {
    if (!episode) {
      return;
    }
    releaseEpisodeSaveLock();
    loadFromEpisode(episode);
    setIsEditVisible(true);
  }, [episode, loadFromEpisode, releaseEpisodeSaveLock]);

  const handleCloseEdit = useCallback(() => {
    releaseEpisodeSaveLock();
    resetEpisodeForm();
    setIsEditVisible(false);
  }, [releaseEpisodeSaveLock, resetEpisodeForm]);

  const handleSaveEdit = useCallback(() => {
    if (episodeSaveLockRef.current) {
      return;
    }
    episodeSaveLockRef.current = true;
    setEpisodeSaving(true);
    if (!myselfId) {
      releaseEpisodeSaveLock();
      episodeForm.setFormError('本人が設定されていません。');
      Alert.alert('エラー', '本人が設定されていません。');
      return;
    }
    const editingId = episodeForm.editingEpisodeId;
    if (!editingId) {
      releaseEpisodeSaveLock();
      return;
    }
    const payload = episodeForm.buildSavePayload();
    if (!payload) {
      releaseEpisodeSaveLock();
      return;
    }
    if (!guardEpisodeShareOnline(payload.visibilityMode)) {
      releaseEpisodeSaveLock();
      return;
    }
    const resolved = resolveEpisodeSaveEventId(payload, () => {
      Alert.alert('エラー', EVENT_CREATE_FAILED_MESSAGE);
      episodeForm.setFormError(EVENT_CREATE_FAILED_MESSAGE);
    });
    if (!resolved.ok) {
      releaseEpisodeSaveLock();
      return;
    }
    const { createLinkedEvent: _createLinkedEvent, eventId: _formEventId, ...episodeFields } =
      payload;
    const updated = updateEpisode(myselfId, editingId, {
      ...episodeFields,
      eventId: resolved.eventId,
      pendingReview: false,
    });
    if (!updated) {
      releaseEpisodeSaveLock();
      episodeForm.setFormError('エピソードの更新に失敗しました。');
      Alert.alert('エラー', 'エピソードの更新に失敗しました。');
      return;
    }
    registerSavedEpisodeTag(episodeFields.tag);
    episodeForm.persistPhotos(editingId, true);
    void afterEpisodeSavedLocally(editingId).finally(() => {
      episodeForm.forgetDraft();
      episodeForm.reset();
      setIsEditVisible(false);
      loadData();
      releaseEpisodeSaveLock();
    });
  }, [episodeForm, loadData, myselfId, releaseEpisodeSaveLock]);

  const handleSaveEditRef = useRef(handleSaveEdit);
  handleSaveEditRef.current = handleSaveEdit;
  const handleEditRef = useRef(handleEdit);
  handleEditRef.current = handleEdit;

  const headerRight = useMemo(() => {
    if (isEditVisible) {
      return (
        <Pressable
          onPress={() => handleSaveEditRef.current()}
          disabled={episodeSaving}
          accessibilityLabel={episodeForm.editingEpisodeId ? '更新' : '保存'}
          hitSlop={8}
        >
          <Text style={[styles.headerSaveText, { color: kit.topBarText }, episodeSaving ? { opacity: 0.55 } : null]}>
            {episodeForm.editingEpisodeId ? '更新' : '保存'}
          </Text>
        </Pressable>
      );
    }
    return canManage ? (
      <Pressable
        style={[
          episodeDetailTopBarButtonStyles.button,
          { borderColor: editButtonBorderColor },
        ]}
        onPress={() => handleEditRef.current()}
        accessibilityLabel="編集"
        hitSlop={8}
      >
        <Ionicons name="pencil-outline" size={18} color={kit.topBarText} />
      </Pressable>
    ) : null;
  }, [
    canManage,
    editButtonBorderColor,
    episodeForm.editingEpisodeId,
    episodeSaving,
    isEditVisible,
    kit.topBarText,
  ]);

  const handleDescriptionChange = useCallback(
    (next: string) => {
      if (!episode || !myselfId || !canManage) {
        return;
      }
      const updated = updateEpisode(myselfId, episode.id, episodeToInput(episode, next));
      if (!updated) {
        Alert.alert('エラー', '説明の更新に失敗しました。');
        return;
      }
      setEpisode({ ...episode, description: next });
      void republishSharedEpisodeIfPublished(episode.id);
      scheduleOwnedEpisodeSync(episode.id);
    },
    [canManage, episode, myselfId]
  );

  const handleDelete = () => {
    Alert.alert('確認', '本当に削除しますか？', [
      { text: 'キャンセル', style: 'cancel' },
      {
        text: '削除',
        style: 'destructive',
        onPress: () => {
          const deleted = deleteEpisode(recordOwnerId, episodeId);
          if (!deleted) {
            Alert.alert('エラー', 'エピソードの削除に失敗しました。');
            return;
          }
          scheduleOwnedEpisodeDelete(episodeId);
          popCurrentTabScreen();
        },
      },
    ]);
  };

  return (
    <>
      <SubToolScreenTemplate
        title={isEditVisible ? 'エピソードを編集' : 'エピソード'}
        onBack={
          isEditVisible
            ? () => {
                if (episodeSaving) {
                  return;
                }
                episodeForm.requestDismiss(handleCloseEdit);
              }
            : handleBack
        }
        right={headerRight}
        titleFramed={false}
        useScreenPadding={false}
        scrollContentStyle={[
          styles.mainScrollContentPreview,
          bottomNavClearance > 0 ? { paddingBottom: bottomNavClearance } : null,
        ]}
      >
        {!episode ? (
          <View style={styles.missingContainer}>
            <Text style={[styles.missingText, contentMutedTextStyle(content)]}>
              エピソードが見つかりませんでした。
            </Text>
          </View>
        ) : (
          <View>
            {isIncomingShared && episode.authorFriendId.trim() ? (
              <EpisodeByline
                variant="heading"
                name={
                  friendNameById.get(episode.authorFriendId.trim()) ??
                  episode.authorFriendId.trim()
                }
                friendId={episode.authorFriendId.trim()}
                photoUri={friendPhotoById.get(episode.authorFriendId.trim()) ?? null}
                style={styles.sharedDetailAuthor}
              />
            ) : null}
          <View style={isIncomingShared ? styles.sharedDetailWithLine : undefined}>
            {isIncomingShared ? (
              <View pointerEvents="none" style={styles.sharedDetailRail}>
                <View style={[styles.sharedDetailLine, { backgroundColor: content.contentDivider }]} />
              </View>
            ) : null}
            <View style={isIncomingShared ? styles.sharedDetailBody : undefined}>
              <EpisodeListCard
              embedded
                titleMultiline
                titleInset
                title={episode.title}
                date={episode.date}
                dateLabel={formatEpisodeDateTimeForDetail(episode.date, episode.time)}
                episodeTag={episode.tag}
                chips={chips}
                visibility={visibility}
                visibilityMode={episode.visibilityMode}
                revealLimitedAudience={canManage && episode.visibilityMode === 'limited'}
                unfilled={episode.pendingReview === true}
                eventTitle={parentEvent?.title.trim() || null}
                eventEpisodeTag={parentEvent?.episodeTag}
                onEventPress={
                  parentEvent
                    ? () =>
                        router.push({
                          pathname: '/event-detail',
                          params: { eventId: parentEvent.id },
                        })
                    : undefined
                }
                style={[
                  styles.episodeHeaderPreview,
                  isIncomingShared ? styles.episodeHeaderAfterAuthor : null,
                ]}
              />

              {hasPhotos ? (
                <>
                  <SectionDivider style={sectionDividerStyle} />
                  <PanelSection style={styles.detailSection}>
                    <View style={[styles.photoViewport, { height: photoFrameHeight }]}>
                      <ScrollView
                        horizontal
                        showsHorizontalScrollIndicator={false}
                        contentContainerStyle={styles.photoScrollContent}
                      >
                        {photos.map((photo, index) => renderPhotoFrame(photo, index))}
                      </ScrollView>
                    </View>
                  </PanelSection>
                </>
              ) : null}

              {hasDescription ? (
                <>
                  <SectionDivider style={sectionDividerStyle} />
                  <PanelSection style={styles.detailSection}>
                    <View style={styles.memoInset}>
                      <NoteBlockView
                        value={episode.description}
                        textStyle={[styles.descriptionText, contentTextStyle(content)]}
                        onChangeValue={canManage ? handleDescriptionChange : undefined}
                      />
                    </View>
                  </PanelSection>
                </>
              ) : null}

              {canManage ? (
              <>
              <SectionDivider style={sectionDividerStyle} />
              <PanelSection style={styles.detailSection}>
                <View style={styles.memoInset}>
                  <Text style={[styles.privateMemoLabel, contentTextStyle(content)]}>非公開メモ</Text>
                  <Text style={[styles.privateMemoPlaceholder, contentMutedTextStyle(content)]}>
                    非公開メモ（近日実装予定）
                  </Text>
                </View>
              </PanelSection>
              </>
              ) : null}

            {canManage ? (
              <Pressable
                style={styles.deleteLinkWrap}
                onPress={handleDelete}
                accessibilityLabel="エピソードを削除"
                hitSlop={8}
              >
                <Text style={styles.deleteLinkText}>エピソードを削除</Text>
              </Pressable>
            ) : null}
            </View>
          </View>
          </View>
        )}
      </SubToolScreenTemplate>

      <Modal
        transparent
        animationType="fade"
        visible={lightboxPhoto !== null}
        onRequestClose={() => setLightboxPhoto(null)}
      >
        <View style={styles.lightboxBackdrop}>
          <Pressable style={styles.lightboxBackdropPress} onPress={() => setLightboxPhoto(null)} />
          {lightboxPhoto ? (
            <Image source={{ uri: lightboxPhoto }} style={styles.lightboxImage} resizeMode="contain" />
          ) : null}
          <Pressable style={styles.lightboxCloseButton} onPress={() => setLightboxPhoto(null)}>
            <Text style={styles.lightboxCloseButtonText}>閉じる</Text>
          </Pressable>
        </View>
      </Modal>

      <EpisodeFormOverlay
        visible={isEditVisible}
        form={episodeForm}
        friends={friends}
        affiliationOptions={affiliationOptions}
        experienceOptions={experienceOptions}
        episodeTagOptions={episodeTagOptions}
        onClose={handleCloseEdit}
        onSave={handleSaveEdit}
        saving={episodeSaving}
        useTopBar={false}
      />
    </>
  );
}

const styles = StyleSheet.create({
  mainScrollContentPreview: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  missingContainer: {
    flex: 1,
    paddingHorizontal: LIST_HORIZONTAL_INSET,
    paddingTop: 24,
    justifyContent: 'center',
  },
  missingText: {
    fontSize: 15,
    color: Theme.textSecondary,
    textAlign: 'center',
  },
  headerSaveText: {
    fontSize: 15,
    fontWeight: '700',
  },
  episodeHeaderPreview: {
    paddingTop: 14,
  },
  episodeHeaderAfterAuthor: {
    paddingTop: 4,
  },
  sharedDetailAuthor: {
    paddingLeft: 12,
    paddingTop: 14,
    marginBottom: 4,
  },
  sharedDetailWithLine: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  sharedDetailRail: {
    width: 18,
    alignItems: 'flex-end',
    paddingTop: 4,
  },
  sharedDetailLine: {
    width: 1.5,
    flex: 1,
    borderRadius: 1,
  },
  sharedDetailBody: {
    flex: 1,
    minWidth: 0,
  },
  detailSection: {
    paddingVertical: 10,
  },
  memoInset: {
    marginHorizontal: EPISODE_DETAIL_SIDE_INSET,
  },
  descriptionText: {
    fontSize: 14,
    color: '#1e293b',
    lineHeight: 22,
  },
  photoViewport: {
    width: '100%',
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  photoScrollContent: {
    alignItems: 'center',
    minHeight: '100%',
  },
  photoFrame: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: Theme.textPrimary,
    borderRadius: 6,
    borderWidth: 0.5,
    borderColor: Theme.inputBorder,
    overflow: 'hidden',
  },
  photoFrameSpaced: {
    marginLeft: PHOTO_GAP,
  },
  photoImage: {
    width: '100%',
    height: '100%',
    backgroundColor: Theme.textPrimary,
  },
  privateMemoLabel: {
    fontSize: Typography.base,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 8,
  },
  privateMemoPlaceholder: {
    fontSize: 14,
    color: '#94a3b8',
  },
  deleteLinkWrap: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.55)',
    backgroundColor: 'rgba(248, 113, 113, 0.12)',
  },
  deleteLinkText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#f87171',
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 48,
  },
  lightboxBackdropPress: {
    ...StyleSheet.absoluteFill,
  },
  lightboxImage: {
    width: '100%',
    height: '80%',
  },
  lightboxCloseButton: {
    position: 'absolute',
    top: 52,
    right: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: Radius.sm,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  lightboxCloseButtonText: {
    color: Theme.bgSurface,
    fontSize: 14,
    fontWeight: '700',
  },
});
