import { v4 as uuidv4 } from 'uuid';
import type { Episode, EpisodeParticipant, EpisodeVisibilityEntry } from '@/types';
import { getAllFriends, getEpisodePhotos, initializeDatabase } from '@/db';
import {
  dequeuePendingOwnedDelete,
  enqueuePendingOwnedDelete,
} from '@/lib/pendingOwnedDeletes';
import { getSupabaseClient } from '@/lib/supabase';
import {
  removeOwnedEpisodePhotoFiles,
  syncOwnedEpisodePhotoUpload,
} from '@/lib/identityPhotoStorage';
import { unpublishSharedEpisode } from '@/lib/sharedEpisodeSync';

export type OwnedEpisodeSyncResult = {
  skipped: boolean;
  errorMessage: string | null;
};

type OwnedEpisodeRow = {
  id: string;
  owner_id: string;
  local_episode_id: string;
  author_friend_id: string;
  title: string;
  date: string;
  time: string | null;
  description: string;
  visibility_mode: string;
  participant_entries: EpisodeParticipant[];
  visibility_entries: EpisodeVisibilityEntry[];
  local_event_id: string | null;
  is_auto_generated: boolean;
  pending_review: boolean;
  pending_review_dismissed: boolean;
  tag: string | null;
  location_tag: string | null;
  updated_at: string;
  deleted_at: null;
  sync_version: number;
};

const collectUniqueEpisodes = (): Episode[] => {
  const byId = new Map<string, Episode>();
  getAllFriends().forEach((friend) => {
    (friend.episodes ?? []).forEach((episode) => {
      const id = episode?.id?.trim() ?? '';
      if (id && !byId.has(id)) {
        byId.set(id, episode);
      }
    });
  });
  return [...byId.values()];
};

const findEpisodeById = (episodeId: string): Episode | null =>
  collectUniqueEpisodes().find((episode) => episode.id === episodeId) ?? null;

export async function upsertOwnedEpisode(episodeId: string): Promise<OwnedEpisodeSyncResult> {
  const trimmed = episodeId.trim();
  if (!trimmed) {
    return { skipped: true, errorMessage: null };
  }

  const supabase = getSupabaseClient();
  if (!supabase) {
    return { skipped: true, errorMessage: null };
  }

  const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
  if (sessionError) {
    return { skipped: false, errorMessage: sessionError.message };
  }
  const ownerId = sessionData.session?.user.id?.trim() ?? '';
  if (!ownerId) {
    return { skipped: true, errorMessage: null };
  }

  initializeDatabase();
  const episode = findEpisodeById(trimmed);
  if (!episode) {
    return { skipped: true, errorMessage: null };
  }

  const { data: existing, error: readError } = await supabase
    .from('owned_episodes')
    .select('id, sync_version')
    .eq('owner_id', ownerId)
    .eq('local_episode_id', trimmed)
    .maybeSingle();
  if (readError) {
    return { skipped: false, errorMessage: readError.message };
  }
  const nextVersion =
    typeof existing?.sync_version === 'number' && Number.isFinite(existing.sync_version)
      ? Math.floor(existing.sync_version) + 1
      : 1;
  const rowId = typeof existing?.id === 'string' && existing.id.trim() ? existing.id : uuidv4();
  const now = new Date().toISOString();
  const row: OwnedEpisodeRow = {
    id: rowId,
    owner_id: ownerId,
    local_episode_id: trimmed,
    author_friend_id: episode.authorFriendId ?? '',
    title: episode.title ?? '',
    date: episode.date ?? '',
    time: episode.time?.trim() ? episode.time : null,
    description: episode.description ?? '',
    visibility_mode: episode.visibilityMode ?? 'private',
    participant_entries: Array.isArray(episode.participantEntries) ? episode.participantEntries : [],
    visibility_entries: Array.isArray(episode.visibilityEntries) ? episode.visibilityEntries : [],
    local_event_id: episode.eventId?.trim() ? episode.eventId.trim() : null,
    is_auto_generated: episode.isAutoGenerated === true,
    pending_review: episode.pendingReview === true,
    pending_review_dismissed: episode.pendingReviewDismissed === true,
    tag: episode.tag?.trim() ? episode.tag : null,
    location_tag: episode.locationTag?.trim() ? episode.locationTag : null,
    updated_at: now,
    deleted_at: null,
    sync_version: nextVersion,
  };

  const { error: upsertError } = await supabase
    .from('owned_episodes')
    .upsert(row, { onConflict: 'owner_id,local_episode_id' });
  if (upsertError) {
    return { skipped: false, errorMessage: upsertError.message };
  }

  const { data: existingPhotos } = await supabase
    .from('owned_episode_photos')
    .select('local_photo_id, photo_path')
    .eq('owner_id', ownerId)
    .eq('local_episode_id', trimmed);
  const localPhotos = getEpisodePhotos(trimmed);

  const photoRows: Array<{
    owner_id: string;
    local_episode_id: string;
    local_photo_id: number;
    photo_path: string;
    sort_order: number;
  }> = [];
  for (const photo of localPhotos) {
    const uploaded = await syncOwnedEpisodePhotoUpload(
      supabase,
      ownerId,
      trimmed,
      photo.id,
      photo.photoUri
    );
    if (uploaded.unreadable) {
      console.warn('skip unreadable episode photo', trimmed, photo.id, uploaded.errorMessage);
      continue;
    }
    if (uploaded.errorMessage || !uploaded.path) {
      return {
        skipped: false,
        errorMessage: uploaded.errorMessage ?? 'エピソード写真のアップロードに失敗しました',
      };
    }
    photoRows.push({
      owner_id: ownerId,
      local_episode_id: trimmed,
      local_photo_id: Number(photo.id),
      photo_path: uploaded.path,
      sort_order: Number(photo.sortOrder) || 0,
    });
  }

  const keepPaths = new Set(photoRows.map((row) => row.photo_path));
  const stalePaths = (existingPhotos ?? [])
    .map((photo) => (typeof photo.photo_path === 'string' ? photo.photo_path : ''))
    .filter((path) => path && !keepPaths.has(path));
  if (stalePaths.length > 0) {
    await removeOwnedEpisodePhotoFiles(supabase, stalePaths);
  }
  const { error: deletePhotosError } = await supabase
    .from('owned_episode_photos')
    .delete()
    .eq('owner_id', ownerId)
    .eq('local_episode_id', trimmed);
  if (deletePhotosError) {
    return { skipped: false, errorMessage: deletePhotosError.message };
  }
  if (photoRows.length > 0) {
    const { error: insertPhotosError } = await supabase.from('owned_episode_photos').insert(photoRows);
    if (insertPhotosError) {
      return { skipped: false, errorMessage: insertPhotosError.message };
    }
  }

  return { skipped: false, errorMessage: null };
}

export async function markOwnedEpisodeDeleted(episodeId: string): Promise<OwnedEpisodeSyncResult> {
  const trimmed = episodeId.trim();
  if (!trimmed) {
    return { skipped: true, errorMessage: null };
  }
  const supabase = getSupabaseClient();
  if (!supabase) {
    return { skipped: true, errorMessage: null };
  }
  const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
  if (sessionError) {
    return { skipped: false, errorMessage: sessionError.message };
  }
  const ownerId = sessionData.session?.user.id?.trim() ?? '';
  if (!ownerId) {
    return { skipped: true, errorMessage: null };
  }

  await unpublishSharedEpisode(trimmed);

  const { data: existingPhotos } = await supabase
    .from('owned_episode_photos')
    .select('photo_path')
    .eq('owner_id', ownerId)
    .eq('local_episode_id', trimmed);
  const paths = (existingPhotos ?? [])
    .map((photo) => (typeof photo.photo_path === 'string' ? photo.photo_path : ''))
    .filter(Boolean);
  await removeOwnedEpisodePhotoFiles(supabase, paths);
  await supabase
    .from('owned_episode_photos')
    .delete()
    .eq('owner_id', ownerId)
    .eq('local_episode_id', trimmed);

  const now = new Date().toISOString();
  const { error } = await supabase
    .from('owned_episodes')
    .update({ deleted_at: now, updated_at: now })
    .eq('owner_id', ownerId)
    .eq('local_episode_id', trimmed);
  if (error) {
    return { skipped: false, errorMessage: error.message };
  }
  return { skipped: false, errorMessage: null };
}

export async function syncAllOwnedEpisodes(): Promise<OwnedEpisodeSyncResult> {
  const supabase = getSupabaseClient();
  if (!supabase) {
    return { skipped: true, errorMessage: null };
  }
  const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
  if (sessionError) {
    return { skipped: false, errorMessage: sessionError.message };
  }
  if (!sessionData.session?.user.id) {
    return { skipped: true, errorMessage: null };
  }

  initializeDatabase();
  const episodes = collectUniqueEpisodes();
  for (const episode of episodes) {
    const result = await upsertOwnedEpisode(episode.id);
    if (result.errorMessage) {
      return result;
    }
  }
  return { skipped: episodes.length === 0, errorMessage: null };
}

export function scheduleOwnedEpisodeSync(episodeId: string): void {
  void upsertOwnedEpisode(episodeId).then((result) => {
    if (result.errorMessage) {
      console.warn('owned episode sync failed', result.errorMessage);
    }
  });
}

export function scheduleOwnedEpisodeDelete(episodeId: string): void {
  enqueuePendingOwnedDelete('episode', episodeId);
  void markOwnedEpisodeDeleted(episodeId).then((result) => {
    if (!result.errorMessage && !result.skipped) {
      dequeuePendingOwnedDelete('episode', episodeId);
    }
  });
}
