import { BorderWidth, Radius, Spacing, Theme } from '@/constants/theme';
import type { UiKit } from './types';

/** 試作中の UI ルール（現時点は stable と同値。差分実験はここだけを変える） */
export const previewUiKit: UiKit = {
  label: 'preview（試作版）',

  screenBackground: Theme.screenBase,
  panelBackground: Theme.bgSurface,
  panelBorderColor: Theme.border,
  panelBorderRadius: Radius.md,
  panelBorderWidth: BorderWidth.card,

  screenPaddingHorizontal: 0,
  sectionPaddingHorizontal: Spacing.md,
  sectionPaddingVertical: Spacing.sm,
  sectionDividerInset: Spacing.md,

  formLabelWidth: 88,
  formRowGap: Spacing.sm,
  formLabelAlign: 'left',
  inputMinHeight: 44,

  formLayout: 'horizontal',
  formContainer: 'singlePanel',
  formPanelBorderRadius: 0,
  formFieldBorderRadius: 0,
  searchAreaStyle: 'singleBorder',
  searchAreaPadding: 0,
  searchAreaRowGap: 4,
  searchAreaFieldGap: Spacing.sm,
  searchAreaFieldBorderRadius: 6,
  searchAreaShowFieldLabels: true,
  searchAreaDividerGapBefore: Spacing.md,
  searchAreaBottomGap: Spacing.md,
  listItemStyle: 'separateCards',
  listPanelStyle: 'edgeFlat',
  sectionDividerStyle: 'bold2px',
  participantChipStyle: 'fitted',
  participantChipBackground: 'transparent',
  episodeListCardLayout: 'photoRight',
  listScreenPaddingHorizontal: Spacing.sm,
  episodeListPaddingHorizontal: Spacing.sm,
  episodeListCardGap: 8,
  episodeListCardBorderRadius: 6,
  episodeListPhotoLayout: 'tallOne',
  episodeListPhotoSpanRows: 3,
  calendarEventMemoDisplay: 'oneLine',
  calendarMonthLayout: 'scheduleGrid',
  calendarEventTimeDisplay: 'plain',
  calendarScreenPaddingHorizontal: 0,
  calendarEventListPaddingHorizontal: Spacing.sm,
  calendarEventCardGap: 4,
  calendarEventCardBorderRadius: 6,
  calendarEventCardStyle: 'current',
  commonItemsPanelBorderRadius: 0,
  commonItemsContentPaddingHorizontal: Spacing.md,
  friendHomeCardGap: Spacing.sm,
  friendHomeCardNamePaddingVertical: Spacing.xs,
  toolScreenCardBorderRadius: Spacing.sm,
  toolScreenIconBorderRadius: Spacing.sm,
  toolScreenShowSubtitle: false,
  subToolScreenPaddingHorizontal: Spacing.sm,
  friendsScreenBorderRadius: Spacing.sm,
  detailProfileCardStyle: 'card',
  textPrimary: Theme.textPrimary,
  textSecondary: Theme.textSecondary,
  inputBg: Theme.inputBg,
  inputBorder: Theme.inputBorder,
  topBarText: Theme.topBarText,
};
