import { BorderWidth, Radius, ScreenHorizontalInset, Spacing, Theme } from '@/constants/theme';
import type { UiKit } from './types';

/** 現在採用中の UI ルール（現状の見た目・構造を反映） */
export const stableUiKit: UiKit = {
  label: 'stable（採用版）',

  screenBackground: Theme.screenBase,
  panelBackground: Theme.bgSurface,
  panelBorderColor: Theme.border,
  panelBorderRadius: Radius.md,
  panelBorderWidth: BorderWidth.card,

  screenPaddingHorizontal: ScreenHorizontalInset,
  sectionPaddingHorizontal: Spacing.md,
  sectionPaddingVertical: Spacing.sm,
  sectionDividerInset: Spacing.md,

  formLabelWidth: 88,
  formRowGap: Spacing.sm,
  formLabelAlign: 'left',
  inputMinHeight: 44,

  formLayout: 'horizontal',
  formContainer: 'singlePanel',
  formPanelBorderRadius: Radius.md,
  formFieldBorderRadius: 10,
  searchAreaStyle: 'doubleBorder',
  searchAreaPadding: 10,
  searchAreaRowGap: 8,
  searchAreaFieldGap: 8,
  searchAreaFieldBorderRadius: Radius.md,
  searchAreaShowFieldLabels: false,
  searchAreaDividerGapBefore: 0,
  searchAreaBottomGap: 0,
  listItemStyle: 'separateCards',
  listPanelStyle: 'roundedPanel',
  sectionDividerStyle: 'hairline',
  participantChipStyle: 'default',
  participantChipBackground: Theme.accentLight,
  episodeListCardLayout: 'photoRight',
  listScreenPaddingHorizontal: ScreenHorizontalInset,
  episodeListPaddingHorizontal: ScreenHorizontalInset,
  episodeListCardGap: 4,
  episodeListCardBorderRadius: 10,
  episodeListPhotoSpanRows: 2,
  calendarEventMemoDisplay: 'oneLine',
  calendarMonthLayout: 'scheduleGrid',
  calendarEventTimeDisplay: 'badge',
  calendarScreenPaddingHorizontal: ScreenHorizontalInset,
  calendarEventListPaddingHorizontal: 0,
  calendarEventCardGap: 0,
  calendarEventCardBorderRadius: Radius.md,
  commonItemsPanelBorderRadius: 10,
  commonItemsContentPaddingHorizontal: Spacing.md,
  friendHomeCardGap: 10,
  friendHomeCardNamePaddingVertical: 6,
  toolScreenCardBorderRadius: Radius.md,
  toolScreenIconBorderRadius: 20,
  toolScreenShowSubtitle: true,
  subToolScreenPaddingHorizontal: ScreenHorizontalInset,
  friendsScreenBorderRadius: 12,
  textPrimary: Theme.textPrimary,
  textSecondary: Theme.textSecondary,
  inputBg: Theme.inputBg,
  inputBorder: Theme.inputBorder,
  topBarText: Theme.topBarText,
};
