import { StyleSheet } from 'react-native';
import { HomeCardElevation, Radius, ScreenHorizontalInset, Spacing, Theme, Typography } from '@/constants/theme';
import type { DetailThemeColors } from '@/constants/detailThemes';

const EPISODE_PICKER_GAP = 6;

export function createDetailStyles(c: DetailThemeColors) {
  return StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: c.background,
  },
  scrollContent: {
    paddingHorizontal: 0,
    paddingTop: 8,
    paddingBottom: 24,
    gap: 10,
  },
  profileCardShadow: {
    borderRadius: 12,
    marginHorizontal: 6,
    backgroundColor: 'transparent',
    ...HomeCardElevation,
  },
  profileCardOuter: {
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: c.card,
  },
  hero: {
    backgroundColor: c.heroBackground,
    paddingTop: 16,
    paddingHorizontal: 14,
    paddingBottom: 14,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  heroIdentityRow: {
    flexDirection: 'row',
    gap: 12,
  },
  heroPhotoOuterFrame: {
    borderWidth: 2,
    borderRadius: Radius.md,
    overflow: 'hidden',
  },
  heroPhotoInnerFrame: {
    borderWidth: 2,
    borderColor: c.card,
    borderRadius: Radius.md - 2,
    overflow: 'hidden',
  },
  heroPhoto: {
    width: 132,
    height: 132,
  },
  heroPhotoPlaceholder: {
    width: 132,
    height: 132,
    backgroundColor: c.accentLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroPhotoPlaceholderText: {
    fontSize: 12,
    color: c.textMuted,
  },
  heroIdentityCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  heroNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  heroName: {
    flex: 1,
    fontSize: 22,
    fontWeight: '500',
    color: c.textPrimary,
  },
  heroIconActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroEditButton: {
    width: 30,
    height: 30,
    borderRadius: Radius.sm,
    backgroundColor: c.accentLight,
    borderWidth: 1,
    borderColor: c.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroHomeButton: {
    width: 30,
    height: 30,
    borderRadius: Radius.sm,
    backgroundColor: c.accentLight,
    borderWidth: 1,
    borderColor: c.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroNickname: {
    fontSize: 14,
    color: c.accent,
  },
  heroNicknameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroByTag: {
    fontSize: 10,
    color: c.heroByTagText,
    fontWeight: '500',
  },
  heroTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  heroTagMbti: {
    backgroundColor: c.heroTagBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
  },
  heroTagMbtiText: {
    fontSize: 12,
    fontWeight: '500',
    color: c.heroTagText,
  },
  heroTagBirthday: {
    backgroundColor: c.heroTagBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
  },
  heroTagBirthdayText: {
    fontSize: 12,
    fontWeight: '500',
    color: c.heroTagText,
  },
  heroTagCategory: {
    backgroundColor: c.accentLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
  },
  heroTagCategoryText: {
    fontSize: 12,
    fontWeight: '500',
    color: c.textMuted,
  },
  heroDescription: {
    fontSize: 11,
    color: c.textMuted,
    lineHeight: 16,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  heroStatCell: {
    flex: 1,
    backgroundColor: c.accentLight,
    borderWidth: 0.5,
    borderColor: c.statBorder,
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  heroStatLabel: {
    fontSize: 9,
    color: c.textMuted,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  heroStatValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
  },
  heroStatValue: {
    fontSize: 18,
    fontWeight: '500',
    color: c.textPrimary,
  },
  heroStatUnit: {
    fontSize: 10,
    color: c.textMuted,
  },
  heroCompletenessSection: {
    marginTop: 10,
  },
  heroCompletenessHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroCompletenessLabel: {
    fontSize: 9,
    color: c.textMuted,
    letterSpacing: 0.3,
  },
  heroCompletenessPercent: {
    fontSize: 10,
    color: c.barPct,
  },
  heroCompletenessTrack: {
    height: 4,
    backgroundColor: c.barTrack,
    borderRadius: 2,
    marginTop: 4,
    overflow: 'hidden',
  },
  heroCompletenessFill: {
    height: 4,
    backgroundColor: c.barFill,
    borderRadius: 2,
  },
  tabSection: {
    gap: 0,
    backgroundColor: c.heroBackground,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: 'hidden',
  },
  tabTrack: {
    backgroundColor: c.tabTrackBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: c.tabTrackBorder,
    paddingVertical: 1.5,
    paddingHorizontal: 3,
    marginHorizontal: 12,
    marginTop: 2,
    marginBottom: 8,
  },
  tabInner: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 2,
    width: '100%',
  },
  tabPill: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 1,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  tabPillContent: {
    alignItems: 'center',
    gap: 3,
  },
  tabPillCaption: {
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  tabPillCaptionInactive: {
    color: c.tabInactive,
  },
  tabPillCaptionActive: {
    color: c.tabActiveText,
  },
  tabPillIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabPillIconCircleActive: {
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    gap: 12,
  },
  statusRowDivider: {
    borderBottomWidth: 0.5,
    borderBottomColor: c.border,
  },
  statusLabel: {
    width: 56,
    fontSize: Typography.base,
    color: c.textMuted,
    flexShrink: 0,
  },
  statusValue: {
    flex: 1,
    fontSize: Typography.base,
    color: c.textPrimary,
    textAlign: 'right',
  },
  tabContentArea: {
    backgroundColor: c.heroBackground,
    margin: 0,
    paddingTop: 0,
  },
  tabPane: {
    backgroundColor: c.tabPaneBackground,
    marginTop: 0,
    paddingHorizontal: 12,
    paddingTop: 0,
    paddingBottom: 10,
  },
  /** 情報・ステータス用。左右端を tabTrack（marginHorizontal: 12）に揃える。上余白は tabTrack.marginBottom のみ */
  tabContentFrame: {
    marginHorizontal: 12,
    marginTop: 0,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: c.tabTrackBorder,
    borderRadius: 10,
    backgroundColor: c.tabPaneBackground,
    paddingHorizontal: 12,
    paddingTop: 0,
    paddingBottom: 4,
    overflow: 'hidden',
  },
  multiValuePlainContainer: {
    padding: 0,
    backgroundColor: c.bgBase,
  },
  multiValueCard: {
    marginHorizontal: 12,
    marginTop: 0,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: c.tabTrackBorder,
    borderRadius: 10,
    backgroundColor: c.multiValueCardBackground,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    overflow: 'hidden',
  },
  habitInput: {
    borderColor: c.inputBorder,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: c.inputBg,
    color: c.inputText,
    textAlignVertical: 'top',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 8,
    fontSize: 14,
  },
  addHabitButton: {
    alignSelf: 'flex-start',
    backgroundColor: c.habitAddButtonBg,
    borderColor: c.habitAddButtonBorder,
    borderWidth: 1,
    borderRadius: Radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  addHabitButtonText: {
    color: c.textPrimary,
    fontWeight: '700',
    fontSize: Typography.base,
  },
  episodeToolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  episodeFilterField: {
    flex: 1,
    minWidth: 0,
    height: 36,
    backgroundColor: c.bgSurface,
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  episodeParticipantFilterField: {
    gap: 2,
  },
  episodeTitleFilterField: {
    fontSize: Typography.base,
    color: c.textPrimary,
    paddingVertical: 0,
  },
  episodeFilterFieldLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: c.textMuted,
  },
  episodeFilterFieldValue: {
    fontSize: Typography.base,
    color: c.textPrimary,
  },
  episodeToolbarAddButton: {
    height: 36,
    flexShrink: 0,
    backgroundColor: c.primaryButtonBg,
    borderRadius: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  episodeParticipantPickerPanel: {
    marginBottom: 10,
    padding: 10,
    borderWidth: 0.5,
    borderColor: c.border,
    borderRadius: 10,
    backgroundColor: c.bgSurface,
  },
  episodeParticipantPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: EPISODE_PICKER_GAP,
    marginBottom: 10,
  },
  episodePickerSearchButton: {
    alignSelf: 'flex-end',
    minWidth: 72,
    height: 36,
    backgroundColor: c.primaryButtonBg,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  episodePersonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: Radius.sm,
    backgroundColor: c.card,
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  episodePersonCheckbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: c.border,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.bgSurface,
  },
  episodePersonCheckboxChecked: {
    backgroundColor: c.accentLight,
    borderColor: c.accent,
  },
  episodePersonCheckmark: {
    color: c.accent,
    fontSize: 16,
    fontWeight: '900',
  },
  episodePersonName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: c.textPrimary,
  },
  episodeSelectButton: {
    height: 36,
    backgroundColor: c.bgSurface,
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  episodeSelectText: {
    fontSize: Typography.base,
    color: c.textPrimary,
  },
  episodeSelectPlaceholder: {
    fontSize: Typography.base,
    color: c.textMuted,
  },
  episodeSearchInput: {
    height: 36,
    backgroundColor: c.bgSurface,
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: Typography.base,
    color: c.textPrimary,
  },
  episodeSearchButton: {
    minWidth: 58,
    height: 36,
    backgroundColor: c.primaryButtonBg,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  episodeSearchButtonText: {
    color: c.primaryButtonText,
    fontWeight: '500',
    fontSize: Typography.base,
  },
  episodeAddButton: {
    alignSelf: 'flex-end',
    backgroundColor: c.primaryButtonBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 7,
    marginBottom: 10,
  },
  episodeAddButtonText: {
    color: c.primaryButtonText,
    fontWeight: '500',
    fontSize: Typography.base,
  },
  episodeFormCard: {
    backgroundColor: c.bgSurface,
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
    marginBottom: 10,
  },
  episodeTitleDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  episodeInput: {
    minHeight: 38,
    borderColor: c.inputBorder,
    borderWidth: 1,
    borderRadius: Radius.md,
    backgroundColor: c.inputBg,
    color: c.inputText,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontSize: Typography.base,
    marginBottom: 8,
  },
  episodeTitleInput: {
    flex: 1,
  },
  episodeDateInput: {
    width: 130,
    justifyContent: 'center',
  },
  episodeDateText: {
    fontSize: Typography.base,
    color: c.textPrimary,
  },
  episodeDatePlaceholder: {
    fontSize: Typography.base,
    color: c.textMuted,
  },
  datePickerWrap: {
    marginBottom: 8,
    backgroundColor: c.bgBase,
    borderRadius: 10,
    paddingVertical: 4,
  },
  datePickerSelf: {
    alignSelf: 'flex-end',
  },
  datePickerDone: {
    alignSelf: 'flex-end',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: Radius.sm,
    backgroundColor: c.primaryButtonBg,
    marginTop: 8,
  },
  datePickerDoneText: {
    color: c.primaryButtonText,
    fontWeight: '600',
    fontSize: Typography.base,
  },
  episodeParticipantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  episodeParticipantLabel: {
    fontSize: Typography.base,
    color: c.textSecondary,
    fontWeight: '500',
  },
  addParticipantButton: {
    backgroundColor: c.primaryButtonBg,
    borderRadius: Radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addParticipantButtonText: {
    color: c.primaryButtonText,
    fontSize: 12,
    fontWeight: '500',
  },
  ownerRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  ownerRoleLabel: {
    fontSize: Typography.base,
    color: c.textPrimary,
    fontWeight: '700',
  },
  roleToggleButton: {
    backgroundColor: c.bgBase,
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  roleToggleButtonActive: {
    backgroundColor: c.roleToggleActiveBg,
    borderColor: c.accent,
  },
  roleToggleButtonText: {
    color: c.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  roleToggleButtonTextActive: {
    color: c.roleToggleActiveText,
  },
  participantItemCard: {
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
    backgroundColor: c.bgBase,
  },
  participantTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  participantTypeLabel: {
    fontSize: 12,
    color: c.textSecondary,
    fontWeight: '500',
  },
  participantItemTopRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 6,
  },
  participantNameSelect: {
    flex: 1,
  },
  participantRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  participantRoleLabel: {
    fontSize: 12,
    color: c.textPrimary,
    fontWeight: '700',
  },
  episodeDescriptionInput: {
    minHeight: 86,
    borderColor: c.inputBorder,
    borderWidth: 1,
    borderRadius: Radius.md,
    backgroundColor: c.inputBg,
    textAlignVertical: 'top',
    color: c.inputText,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontSize: Typography.base,
    marginBottom: 8,
  },
  episodeCreateButton: {
    alignSelf: 'flex-end',
    backgroundColor: c.primaryButtonBg,
    borderRadius: Radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  episodeCreateButtonText: {
    color: c.primaryButtonText,
    fontWeight: '500',
    fontSize: Typography.base,
  },
  episodeFormActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  episodeCancelButton: {
    backgroundColor: 'transparent',
    borderColor: c.btnGhostBorder,
    borderWidth: 0.5,
    borderRadius: Radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  episodeCancelButtonText: {
    color: c.btnGhostText,
    fontWeight: '500',
    fontSize: Typography.base,
  },
  episodeErrorText: {
    color: '#b91c1c',
    marginBottom: 8,
    fontSize: 12,
  },
  episodeListInset: {
    paddingHorizontal: ScreenHorizontalInset - Spacing.md,
  },
  episodeListEdgeToEdge: {
    marginHorizontal: -12,
    paddingHorizontal: 0,
  },
  episodeCard: {
    backgroundColor: c.episodeBg,
    borderColor: c.episodeBorder,
    borderWidth: 0.5,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 6,
  },
  episodeCardRow1: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  episodeCardTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: Typography.base,
    fontWeight: '700',
    color: c.episodeTitle,
  },
  episodeCardDateText: {
    fontSize: 11,
    color: c.episodeDate,
    flexShrink: 0,
  },
  episodeCardRow2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  episodeParticipantChipList: {
    flex: 1,
    minWidth: 0,
  },
  episodeParticipantTagScroll: {
    flex: 1,
    minWidth: 0,
  },
  episodeParticipantTagWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  episodeParticipantTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderColor: c.border,
    borderWidth: 1,
    borderRadius: 999,
    backgroundColor: c.tagChipBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexShrink: 0,
  },
  episodeParticipantTagMain: {
    borderColor: c.border,
  },
  episodeParticipantTagName: {
    fontSize: 10,
    fontWeight: '500',
    color: c.textPrimary,
  },
  visibilityModeTag: {
    flexShrink: 0,
  },
  visibilityModeIconWrap: {
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  emptyEpisodeText: {
    fontSize: Typography.base,
    color: c.textMuted,
  },
  sayingTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sayingFormCard: {
    backgroundColor: c.bgSurface,
    borderColor: c.border,
    borderWidth: 0.5,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  sayingTextInput: {
    borderColor: c.inputBorder,
    borderWidth: 1,
    borderRadius: Radius.md,
    backgroundColor: c.inputBg,
    color: c.inputText,
    textAlignVertical: 'top',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontSize: Typography.base,
    minHeight: 72,
    marginBottom: 8,
  },
  sayingDateInput: {
    width: '100%',
    marginBottom: 8,
    justifyContent: 'center',
  },
  sayingActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  habitCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: c.traitBg,
    borderWidth: 0.5,
    borderColor: c.traitBorder,
    borderRadius: Radius.md,
    padding: 12,
    marginBottom: 6,
  },
  habitCardAccent: {
    width: 2,
    alignSelf: 'stretch',
    backgroundColor: c.traitAccentLine,
    borderRadius: 1,
  },
  habitCardText: {
    flex: 1,
    fontSize: Typography.base,
    color: c.traitText,
    lineHeight: 20,
    paddingLeft: 10,
  },
  sayingQuoteCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: c.traitBg,
    borderWidth: 0.5,
    borderColor: c.traitBorder,
    borderTopRightRadius: Radius.md,
    borderBottomRightRadius: Radius.md,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    padding: 12,
    marginBottom: 8,
  },
  sayingQuoteAccent: {
    width: 2,
    alignSelf: 'stretch',
    backgroundColor: c.traitAccentLine,
    borderRadius: 1,
  },
  sayingQuoteBody: {
    flex: 1,
    paddingLeft: 10,
  },
  sayingQuoteText: {
    fontSize: Typography.base,
    color: c.quoteText,
    fontStyle: 'italic',
    lineHeight: 20,
  },
  sayingQuoteDate: {
    fontSize: 10,
    color: c.quoteDateText,
    marginTop: 4,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: c.overlay,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  modalCard: {
    backgroundColor: c.bgSurface,
    borderRadius: Radius.md,
    padding: 14,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: c.textPrimary,
    marginBottom: 10,
  },
  modalOptions: {
    marginBottom: 10,
  },
  modalOption: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: Radius.sm,
  },
  modalOptionSelected: {
    backgroundColor: c.modalOptionSelectedBg,
  },
  modalOptionText: {
    fontSize: 14,
    color: c.textPrimary,
  },
  modalCloseButton: {
    alignSelf: 'flex-end',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: Radius.sm,
    backgroundColor: c.border,
  },
  modalCloseButtonText: {
    color: c.textPrimary,
    fontWeight: '600',
  },
  multiValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 8,
    marginBottom: 8,
    gap: 10,
  },
  multiValueRowWithDivider: {
    borderBottomWidth: 0.5,
    borderBottomColor: c.border,
  },
  multiValueRowLast: {
    paddingBottom: 8,
    marginBottom: 0,
  },
  multiValueLabel: {
    width: 40,
    fontSize: Typography.base,
    color: c.textMuted,
    flexShrink: 0,
  },
  multiValueChipArea: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    justifyContent: 'flex-start',
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: Radius.full,
  },
  chipText: {
    fontSize: Typography.sm,
    fontWeight: '500',
  },
  missingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 10,
  },
  missingText: {
    fontSize: 15,
    color: Theme.topBarText,
  },
  backButton: {
    backgroundColor: c.modalCloseButtonBg,
    borderRadius: Radius.sm,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: c.textPrimary,
    fontWeight: '600',
  },
});
}
