import { Alert } from 'react-native';
import { initializeDatabase, getEvent, updateEpisode, type EpisodeInput } from '../db';
import type { Episode, EpisodeParticipant } from '../types';
import { normalizeEpisodeTag } from './episodeHelpers';
import { formatDateKey, getLocalDateKeysForEvent } from './eventHelpers';
import {
  createEventFromEpisode,
  findMatchingEventsForEpisode,
  formatEpisodeEventMatchLabel,
  type EpisodeEventMatch,
} from './eventEpisodeSync';

export type EpisodeEventLinkInput = {
  title: string;
  date: string;
  description: string;
  participantEntries: EpisodeParticipant[];
  tag?: string | null;
};

export const EVENT_CREATE_FAILED_MESSAGE =
  '予定の作成に失敗しました。エピソードは保存されていません。';

export const buildEpisodeEventLinkInput = (episode: Episode): EpisodeEventLinkInput => ({
  title: episode.title,
  date: episode.date,
  description: episode.description,
  participantEntries: episode.participantEntries,
  tag: episode.tag ?? null,
});

export const buildEpisodeEventLinkInputFromSavePayload = (payload: {
  title: string;
  date: string;
  description: string;
  participantEntries: EpisodeParticipant[];
  tag?: string | null;
}): EpisodeEventLinkInput => ({
  title: payload.title,
  date: payload.date,
  description: payload.description,
  participantEntries: payload.participantEntries,
  tag: payload.tag ?? null,
});

const resolveDateForLinkedEvent = (episodeDate: string, eventId: string): string => {
  const event = getEvent(eventId);
  if (!event) {
    return episodeDate;
  }
  const keys = getLocalDateKeysForEvent(event);
  if (keys.length === 0) {
    return episodeDate;
  }
  if (keys.length === 1) {
    return keys[0];
  }
  if (keys.includes(episodeDate)) {
    return episodeDate;
  }
  return keys[0] ?? formatDateKey(new Date(event.startAt));
};

const buildEpisodeInputFromEpisode = (episode: Episode, eventId: string): EpisodeInput => {
  const normalizedEventId = eventId.trim();
  const event = getEvent(normalizedEventId);
  const existingTag = normalizeEpisodeTag(episode.tag);
  return {
    title: episode.title,
    date: resolveDateForLinkedEvent(episode.date, normalizedEventId),
    time: episode.time ?? null,
    description: episode.description,
    visibilityMode: episode.visibilityMode,
    participantEntries: episode.participantEntries,
    visibilityEntries: episode.visibilityEntries,
    eventId: normalizedEventId,
    // 既存タグがあれば維持。空のときだけ予定タグを初期コピー
    tag: existingTag ?? normalizeEpisodeTag(event?.episodeTag),
    isAutoGenerated: episode.isAutoGenerated,
    pendingReview: episode.pendingReview,
  };
};

export const createEventIdForEpisodeInput = (input: EpisodeEventLinkInput): string | null => {
  const event = createEventFromEpisode(input);
  return event?.id?.trim() || null;
};

export type ResolveEpisodeSaveEventIdResult =
  | { ok: true; eventId: string | null }
  | { ok: false };

/** Resolve calendar event id from form choice (none / existing / create new). */
export const resolveEpisodeSaveEventId = (
  payload: {
    title: string;
    date: string;
    description: string;
    participantEntries: EpisodeParticipant[];
    tag?: string | null;
    eventId: string | null;
    createLinkedEvent: boolean;
  },
  onEventCreateFailed?: () => void
): ResolveEpisodeSaveEventIdResult => {
  if (payload.createLinkedEvent) {
    const eventId = createEventIdForEpisodeInput(
      buildEpisodeEventLinkInputFromSavePayload(payload)
    );
    if (!eventId) {
      if (onEventCreateFailed) {
        onEventCreateFailed();
      } else {
        showEventCreateFailedAlert();
      }
      return { ok: false };
    }
    return { ok: true, eventId };
  }
  return { ok: true, eventId: payload.eventId?.trim() || null };
};

const showEventCreateFailedAlert = (): void => {
  Alert.alert('エラー', EVENT_CREATE_FAILED_MESSAGE);
};

const showSingleMatchAlert = (
  input: EpisodeEventLinkInput,
  match: EpisodeEventMatch,
  onResolved: (eventId: string) => void,
  onEventCreateFailed?: () => void
): void => {
  Alert.alert(
    '予定が見つかりました',
    `${formatEpisodeEventMatchLabel(match.event, input.date)}の予定が見つかりました。このエピソードをこの予定に紐づけますか？`,
    [
      {
        text: 'やめる',
        style: 'cancel',
      },
      {
        text: '新規作成',
        onPress: () => {
          const eventId = createEventIdForEpisodeInput(input);
          if (eventId) {
            onResolved(eventId);
            return;
          }
          if (onEventCreateFailed) {
            onEventCreateFailed();
          } else {
            showEventCreateFailedAlert();
          }
        },
      },
      {
        text: 'この予定に紐づけ',
        onPress: () => onResolved(match.event.id),
      },
    ]
  );
};

export type NewEpisodeEventLinkHandlers = {
  onResolved: (eventId: string) => void;
  onMultipleMatches: (matches: EpisodeEventMatch[]) => void;
  onEventCreateFailed?: () => void;
};

/** 新規エピソード保存前: 既存予定への紐づけ or 新規予定作成（予定なし保存は不可） */
export const runNewEpisodeEventLinkFlow = (
  input: EpisodeEventLinkInput,
  handlers: NewEpisodeEventLinkHandlers
): void => {
  initializeDatabase();
  const matches = findMatchingEventsForEpisode(input.date, input.participantEntries);

  if (matches.length === 0) {
    const eventId = createEventIdForEpisodeInput(input);
    if (eventId) {
      handlers.onResolved(eventId);
      return;
    }
    if (handlers.onEventCreateFailed) {
      handlers.onEventCreateFailed();
    } else {
      showEventCreateFailedAlert();
    }
    return;
  }

  if (matches.length === 1) {
    showSingleMatchAlert(input, matches[0], handlers.onResolved, handlers.onEventCreateFailed);
    return;
  }

  handlers.onMultipleMatches(matches);
};

export const applyEventIdToEpisode = (
  episode: Episode,
  authorFriendId: string,
  eventId: string
): boolean =>
  updateEpisode(authorFriendId, episode.id, buildEpisodeInputFromEpisode(episode, eventId.trim()));

export const runEpisodeEventLinkFlow = (
  input: EpisodeEventLinkInput,
  handlers: {
    onLinked: (eventId: string) => void;
    onMultipleMatches: (matches: EpisodeEventMatch[]) => void;
    onEventCreateFailed?: () => void;
  }
): void => {
  initializeDatabase();
  const matches = findMatchingEventsForEpisode(input.date, input.participantEntries);

  if (matches.length === 0) {
    const eventId = createEventIdForEpisodeInput(input);
    if (eventId) {
      handlers.onLinked(eventId);
      return;
    }
    if (handlers.onEventCreateFailed) {
      handlers.onEventCreateFailed();
    } else {
      showEventCreateFailedAlert();
    }
    return;
  }

  if (matches.length === 1) {
    showSingleMatchAlert(input, matches[0], handlers.onLinked, handlers.onEventCreateFailed);
    return;
  }

  handlers.onMultipleMatches(matches);
};

export const createEventAndLinkEpisode = (
  input: EpisodeEventLinkInput,
  onLinked: (eventId: string) => void,
  onEventCreateFailed?: () => void
): void => {
  const eventId = createEventIdForEpisodeInput(input);
  if (eventId) {
    onLinked(eventId);
    return;
  }
  if (onEventCreateFailed) {
    onEventCreateFailed();
  } else {
    showEventCreateFailedAlert();
  }
};
