import {
  createEpisode,
  getEventParticipants,
  getMyself,
  getPastEventsPendingEpisodeConversion,
  hasAutoGeneratedEpisodeForEvent,
  markEventAutoEpisodeCreated,
} from '../db';
import type { EpisodeParticipant } from '../types';
import { formatDateKey } from './eventHelpers';
import { profileIdsToFriendIds } from './eventParticipantHelpers';

export const convertPastEventsToAutoEpisodes = (): void => {
  const myselfId = getMyself();
  if (!myselfId) {
    return;
  }

  const events = getPastEventsPendingEpisodeConversion(new Date().toISOString());

  events.forEach((event) => {
    if (hasAutoGeneratedEpisodeForEvent(event.id)) {
      markEventAutoEpisodeCreated(event.id);
      return;
    }

    const participantProfileIds = getEventParticipants(event.id).map((participant) => participant.profileId);
    if (participantProfileIds.length === 0) {
      return;
    }

    const participantFriendIds = profileIdsToFriendIds(participantProfileIds);
    const participantEntries: EpisodeParticipant[] = participantFriendIds.map((friendId) => ({
      kind: 'individual',
      value: friendId,
    }));

    const date = formatDateKey(new Date(event.startAt));
    const description = event.memo?.trim() ?? '';

    const created = createEpisode({
      title: event.title,
      date,
      description,
      visibilityMode: 'private',
      participantEntries,
      visibilityEntries: [],
      eventId: event.id,
      isAutoGenerated: true,
      pendingReview: true,
      tag: event.episodeTag,
    });

    if (!created) {
      return;
    }

    markEventAutoEpisodeCreated(event.id);
  });
};
