import {
  getEpisodeByEventId,
  getEpisodeParticipantFriendIds,
  getEvent,
  getEventParticipants,
  getMyself,
  updateEpisode,
  updateEvent,
  type EpisodeInput,
} from '../db';
import type { Episode, EpisodeParticipant } from '../types';
import { formatDateKey, getLocalDateKeysForEvent, parseDateKey } from './eventHelpers';
import { normalizeEpisodeTag } from './episodeHelpers';
import {
  friendIdsToProfileIds,
  profileIdsToFriendIds,
  syncEventParticipants,
} from './eventParticipantHelpers';

let isSyncingEventEpisode = false;

export const isEventEpisodeSyncInProgress = (): boolean => isSyncingEventEpisode;

const sortedFriendIds = (friendIds: string[]): string[] =>
  [...new Set(friendIds.map((id) => id.trim()).filter((id) => id.length > 0))].sort();

const participantFriendIdsFromEvent = (eventId: string): string[] => {
  const profileIds = getEventParticipants(eventId).map((participant) => participant.profileId);
  return sortedFriendIds(profileIdsToFriendIds(profileIds));
};

const participantFriendIdsFromEpisode = (participantEntries: EpisodeParticipant[]): string[] =>
  sortedFriendIds(getEpisodeParticipantFriendIds({ participantEntries }));

const friendIdsEqual = (left: string[], right: string[]): boolean =>
  left.length === right.length && left.every((value, index) => value === right[index]);

const toIndividualParticipantEntries = (friendIds: string[]): EpisodeParticipant[] =>
  friendIds.map((friendId) => ({ kind: 'individual', value: friendId }));

const buildEpisodeInputFromEpisode = (
  episode: Episode,
  overrides: Partial<Pick<EpisodeInput, 'date' | 'participantEntries' | 'eventId' | 'tag'>>
): EpisodeInput => ({
  title: episode.title,
  date: overrides.date ?? episode.date,
  description: episode.description,
  visibilityMode: episode.visibilityMode,
  participantEntries: overrides.participantEntries ?? episode.participantEntries,
  visibilityEntries: episode.visibilityEntries,
  eventId: overrides.eventId ?? episode.eventId,
  tag: overrides.tag ?? episode.tag ?? null,
  isAutoGenerated: episode.isAutoGenerated,
  pendingReview: episode.pendingReview,
});

export const syncLinkedEpisodesFromEvent = (eventId: string): void => {
  if (isSyncingEventEpisode) {
    return;
  }

  const normalizedEventId = eventId.trim();
  if (!normalizedEventId) {
    return;
  }

  const event = getEvent(normalizedEventId);
  const episode = getEpisodeByEventId(normalizedEventId);
  if (!event || !episode) {
    return;
  }

  const allowedDateKeys = getLocalDateKeysForEvent(event);
  let nextDate = episode.date;
  if (!allowedDateKeys.includes(episode.date)) {
    nextDate = formatDateKey(new Date(event.startAt));
  }

  const nextParticipantFriendIds = participantFriendIdsFromEvent(normalizedEventId);
  const currentParticipantFriendIds = participantFriendIdsFromEpisode(episode.participantEntries);
  const nextTag = normalizeEpisodeTag(event.episodeTag);
  const currentTag = normalizeEpisodeTag(episode.tag);
  const dateChanged = nextDate !== episode.date;
  const participantsChanged = !friendIdsEqual(currentParticipantFriendIds, nextParticipantFriendIds);
  const tagChanged = nextTag !== currentTag;

  if (!dateChanged && !participantsChanged && !tagChanged) {
    return;
  }

  const ownerId = episode.authorFriendId.trim() || getMyself() || '';
  if (!ownerId) {
    return;
  }

  isSyncingEventEpisode = true;
  try {
    if (dateChanged) {
      updateEpisode(
        ownerId,
        episode.id,
        buildEpisodeInputFromEpisode(episode, { date: nextDate })
      );
    }
    if (participantsChanged) {
      const episodeForParticipants = dateChanged
        ? { ...episode, date: nextDate }
        : episode;
      updateEpisode(
        ownerId,
        episode.id,
        buildEpisodeInputFromEpisode(episodeForParticipants, {
          participantEntries: toIndividualParticipantEntries(nextParticipantFriendIds),
        })
      );
    }
    if (tagChanged) {
      const episodeForTag = dateChanged
        ? { ...episode, date: nextDate }
        : participantsChanged
          ? {
              ...episode,
              participantEntries: toIndividualParticipantEntries(nextParticipantFriendIds),
            }
          : episode;
      updateEpisode(
        ownerId,
        episode.id,
        buildEpisodeInputFromEpisode(episodeForTag, { tag: nextTag })
      );
    }
  } finally {
    isSyncingEventEpisode = false;
  }
};

export const syncLinkedEventFromEpisode = (episode: Episode, _authorFriendId: string): void => {
  if (isSyncingEventEpisode) {
    return;
  }

  const eventId = episode.eventId?.trim();
  if (!eventId) {
    return;
  }

  const event = getEvent(eventId);
  if (!event) {
    return;
  }

  const nextProfileIds = sortedFriendIds(
    friendIdsToProfileIds(participantFriendIdsFromEpisode(episode.participantEntries))
  );
  const currentProfileIds = sortedFriendIds(
    getEventParticipants(eventId).map((participant) => participant.profileId)
  );
  const participantsChanged = !friendIdsEqual(nextProfileIds, currentProfileIds);

  const nextTag = normalizeEpisodeTag(episode.tag);
  const currentTag = normalizeEpisodeTag(event.episodeTag);
  const tagChanged = nextTag !== currentTag;

  if (!participantsChanged && !tagChanged) {
    return;
  }

  isSyncingEventEpisode = true;
  try {
    if (participantsChanged) {
      syncEventParticipants(eventId, nextProfileIds);
    }
    if (tagChanged) {
      updateEvent(eventId, {
        title: event.title,
        startAt: event.startAt,
        endAt: event.endAt,
        allDay: event.allDay,
        memo: event.memo,
        notifyAt: event.notifyAt,
        notifyEnabled: event.notifyEnabled,
        autoEpisodeCreated: event.autoEpisodeCreated,
        episodeTag: nextTag,
      });
    }
  } finally {
    isSyncingEventEpisode = false;
  }
};

export const getLinkedEventDateBounds = (
  eventId: string | null | undefined
): { minimumDate: Date; maximumDate: Date } | null => {
  const normalizedEventId = eventId?.trim();
  if (!normalizedEventId) {
    return null;
  }
  const event = getEvent(normalizedEventId);
  if (!event) {
    return null;
  }
  const dateKeys = getLocalDateKeysForEvent(event);
  if (dateKeys.length === 0) {
    return null;
  }
  return {
    minimumDate: parseDateKey(dateKeys[0]),
    maximumDate: parseDateKey(dateKeys[dateKeys.length - 1]),
  };
};
