import {
  getEpisodesByEventId,
  getEvent,
  getMyself,
  updateEpisode,
  type EpisodeInput,
} from '../db';
import type { Episode } from '../types';
import { formatDateKey, getLocalDateKeysForEvent, parseDateKey } from './eventHelpers';

let isSyncingEventEpisode = false;

export const isEventEpisodeSyncInProgress = (): boolean => isSyncingEventEpisode;

const buildEpisodeInputFromEpisode = (
  episode: Episode,
  overrides: Partial<Pick<EpisodeInput, 'date' | 'eventId' | 'tag'>>
): EpisodeInput => ({
  title: episode.title,
  date: overrides.date ?? episode.date,
  description: episode.description,
  visibilityMode: episode.visibilityMode,
  participantEntries: episode.participantEntries,
  visibilityEntries: episode.visibilityEntries,
  eventId: overrides.eventId !== undefined ? overrides.eventId : episode.eventId,
  tag: overrides.tag ?? episode.tag ?? null,
  isAutoGenerated: episode.isAutoGenerated,
  pendingReview: episode.pendingReview,
});

/**
 * 予定の期間が変わったとき、範囲外になったエピソード日付だけ開始日へクランプする。
 * タイトル・タグ・本文・参加者は同期しない（フォルダモデル）。
 */
export const clampLinkedEpisodeDatesToEvent = (eventId: string): void => {
  if (isSyncingEventEpisode) {
    return;
  }

  const normalizedEventId = eventId.trim();
  if (!normalizedEventId) {
    return;
  }

  const event = getEvent(normalizedEventId);
  if (!event) {
    return;
  }

  const allowedDateKeys = getLocalDateKeysForEvent(event);
  if (allowedDateKeys.length === 0) {
    return;
  }

  const fallbackDate = formatDateKey(new Date(event.startAt));
  const episodes = getEpisodesByEventId(normalizedEventId);

  isSyncingEventEpisode = true;
  try {
    episodes.forEach((episode) => {
      if (allowedDateKeys.includes(episode.date)) {
        return;
      }
      const ownerId = episode.authorFriendId.trim() || getMyself() || '';
      if (!ownerId) {
        return;
      }
      updateEpisode(
        ownerId,
        episode.id,
        buildEpisodeInputFromEpisode(episode, { date: fallbackDate })
      );
    });
  } finally {
    isSyncingEventEpisode = false;
  }
};

/** @deprecated 互換用。clampLinkedEpisodeDatesToEvent と同じ */
export const syncLinkedEpisodesFromEvent = clampLinkedEpisodeDatesToEvent;

/** エピソード保存時の予定側への書き戻しは行わない（フォルダモデル） */
export const syncLinkedEventFromEpisode = (
  _episode: Episode,
  _authorFriendId: string
): void => {
  // no-op
};

export const getLinkedEventDateBounds = (
  eventId: string | null | undefined
): { minimumDate: Date; maximumDate: Date } | null => {
  const normalizedEventId = eventId?.trim();
  if (!normalizedEventId) {
    return null;
  }
  const event = getEvent(normalizedEventId);
  if (!event) {
    return null;
  }
  const dateKeys = getLocalDateKeysForEvent(event);
  if (dateKeys.length === 0) {
    return null;
  }
  return {
    minimumDate: parseDateKey(dateKeys[0]),
    maximumDate: parseDateKey(dateKeys[dateKeys.length - 1]),
  };
};
