import {
  deleteEpisode,
  getEpisodesByEventId,
  getEvent,
  getMyself,
  updateEpisode,
  type EpisodeInput,
} from '../db';
import type { Episode } from '../types';
import { formatDateKey, getLocalDateKeysForEvent, parseDateKey } from './eventHelpers';

let isSyncingEventEpisode = false;

export const isEventEpisodeSyncInProgress = (): boolean => isSyncingEventEpisode;

const buildEpisodeInputFromEpisode = (
  episode: Episode,
  overrides: Partial<Pick<EpisodeInput, 'date' | 'eventId' | 'tag'>>
): EpisodeInput => ({
  title: episode.title,
  date: overrides.date ?? episode.date,
  time: episode.time ?? null,
  description: episode.description,
  visibilityMode: episode.visibilityMode,
  participantEntries: episode.participantEntries,
  visibilityEntries: episode.visibilityEntries,
  eventId: overrides.eventId !== undefined ? overrides.eventId : episode.eventId,
  tag: overrides.tag ?? episode.tag ?? null,
  isAutoGenerated: episode.isAutoGenerated,
  pendingReview: episode.pendingReview,
  pendingReviewDismissed: episode.pendingReviewDismissed,
});

/**
 * 予定の期間が変わったとき、範囲外になったエピソード日付だけ開始日へクランプする。
 * 開始日が未来になる場合は日付を未来にせず、紐づけを解除する。
 * タイトル・タグ・本文・参加者は同期しない（フォルダモデル）。
 */
export const clampLinkedEpisodeDatesToEvent = (eventId: string): void => {
  if (isSyncingEventEpisode) {
    return;
  }

  const normalizedEventId = eventId.trim();
  if (!normalizedEventId) {
    return;
  }

  const event = getEvent(normalizedEventId);
  if (!event) {
    return;
  }

  const todayKey = formatDateKey(new Date());
  const allowedDateKeys = getLocalDateKeysForEvent(event).filter((key) => key <= todayKey);
  const episodes = getEpisodesByEventId(normalizedEventId);
  const fallbackDate = allowedDateKeys[0] ?? null;

  isSyncingEventEpisode = true;
  try {
    episodes.forEach((episode) => {
      const ownerId = episode.authorFriendId.trim() || getMyself() || '';
      if (!ownerId) {
        return;
      }
      if (allowedDateKeys.includes(episode.date)) {
        return;
      }
      if (!fallbackDate) {
        updateEpisode(
          ownerId,
          episode.id,
          buildEpisodeInputFromEpisode(episode, { eventId: null })
        );
        return;
      }
      updateEpisode(
        ownerId,
        episode.id,
        buildEpisodeInputFromEpisode(episode, { date: fallbackDate })
      );
    });
  } finally {
    isSyncingEventEpisode = false;
  }
};

/** @deprecated 互換用。clampLinkedEpisodeDatesToEvent と同じ */
export const syncLinkedEpisodesFromEvent = clampLinkedEpisodeDatesToEvent;

/** エピソード保存時の予定側への書き戻しは行わない（フォルダモデル） */
export const syncLinkedEventFromEpisode = (
  _episode: Episode,
  _authorFriendId: string
): void => {
  // no-op
};

/** Keep episode dates; clear eventId on all episodes linked to this event. */
export const unlinkEpisodesFromEvent = (eventId: string): void => {
  const normalizedEventId = eventId.trim();
  if (!normalizedEventId) {
    return;
  }
  const episodes = getEpisodesByEventId(normalizedEventId);
  isSyncingEventEpisode = true;
  try {
    episodes.forEach((episode) => {
      const ownerId = episode.authorFriendId.trim() || getMyself() || '';
      if (!ownerId) {
        return;
      }
      updateEpisode(ownerId, episode.id, buildEpisodeInputFromEpisode(episode, { eventId: null }));
    });
  } finally {
    isSyncingEventEpisode = false;
  }
};

/** Delete all episodes linked to this event. */
export const deleteEpisodesLinkedToEvent = (eventId: string): void => {
  const normalizedEventId = eventId.trim();
  if (!normalizedEventId) {
    return;
  }
  const episodes = getEpisodesByEventId(normalizedEventId);
  episodes.forEach((episode) => {
    const ownerId = episode.authorFriendId.trim() || getMyself() || '';
    if (!ownerId) {
      return;
    }
    deleteEpisode(ownerId, episode.id);
  });
};

/**
 * Episode date picker bounds for a linked event.
 * Future dates are excluded (episode dates cannot be after today).
 */
export const getLinkedEventDateBounds = (
  eventId: string | null | undefined
): { minimumDate: Date; maximumDate: Date } | null => {
  const normalizedEventId = eventId?.trim();
  if (!normalizedEventId) {
    return null;
  }
  const event = getEvent(normalizedEventId);
  if (!event) {
    return null;
  }
  const todayKey = formatDateKey(new Date());
  const dateKeys = getLocalDateKeysForEvent(event).filter((key) => key <= todayKey);
  if (dateKeys.length === 0) {
    return null;
  }
  return {
    minimumDate: parseDateKey(dateKeys[0]),
    maximumDate: parseDateKey(dateKeys[dateKeys.length - 1]),
  };
};
