import {
  createEpisode,
  getEventParticipants,
  getMyself,
  getPastEventsPendingEpisodeConversion,
  hasAutoGeneratedEpisodeForEvent,
  markEventAutoEpisodeCreated,
} from '../db';
import type { EpisodeParticipant } from '../types';
import { formatDateKey, formatTimeFromDate } from './eventHelpers';
import { profileIdsToFriendIds } from './eventParticipantHelpers';
import { normalizeEpisodeTime } from './episodeHelpers';

export const convertPastEventsToAutoEpisodes = (): void => {
  const myselfId = getMyself();
  if (!myselfId) {
    return;
  }

  const events = getPastEventsPendingEpisodeConversion(new Date().toISOString());

  events.forEach((event) => {
    if (hasAutoGeneratedEpisodeForEvent(event.id)) {
      markEventAutoEpisodeCreated(event.id);
      return;
    }

    const participantProfileIds = getEventParticipants(event.id).map((participant) => participant.profileId);
    const participantFriendIds = profileIdsToFriendIds(participantProfileIds).filter(
      (friendId) => friendId !== myselfId
    );
    const participantEntries: EpisodeParticipant[] = participantFriendIds.map((friendId) => ({
      kind: 'individual',
      value: friendId,
    }));

    const start = new Date(event.startAt);
    const date = formatDateKey(start);
    const time = event.allDay ? null : normalizeEpisodeTime(formatTimeFromDate(start));
    const description = event.memo?.trim() ?? '';

    const created = createEpisode({
      title: event.title,
      date,
      ...(time ? { time } : {}),
      description,
      visibilityMode: 'private',
      participantEntries,
      visibilityEntries: [],
      eventId: event.id,
      isAutoGenerated: true,
      pendingReview: true,
      tag: event.episodeTag,
      locationTag: event.locationTag,
    });

    if (!created) {
      return;
    }

    markEventAutoEpisodeCreated(event.id);
  });
};
