import { LightTheme } from '@/constants/theme';
import type { DetailDesignBundle, DetailTabDef, InfoChipStyle } from './types';

const c = LightTheme;

const DETAIL_TABS: DetailTabDef[] = [
  { key: '情報', icon: 'book-outline', caption: 'info', color: c.accent },
  { key: 'ステータス', icon: 'stats-chart-outline', caption: 'status', color: c.accent },
  { key: 'エピソード', icon: 'film-outline', caption: 'episode', color: c.accent },
  { key: '習性', icon: 'cat', iconSet: 'material', caption: 'habit', color: c.accent },
  { key: '彼曰く', icon: 'comment-account-outline', iconSet: 'material', caption: 'says', color: c.accent },
  { key: 'メモ', icon: 'notebook', iconSet: 'material', caption: 'note', color: c.accent },
];

const unifiedChip: InfoChipStyle = {
  backgroundColor: c.tagChipBg,
  borderColor: c.tagAffilBorder,
  color: c.tagAffilText,
  borderWidth: 1,
};

export const lightDetailDesign: DetailDesignBundle = {
  variant: 'light',
  label: 'ライト ver',
  tabMode: 'accentOnly',
  colors: {
    background: c.background,
    card: c.card,
    bgBase: c.bgBase,
    bgSurface: c.bgSurface,
    bgElevated: c.bgElevated,
    border: c.border,
    textPrimary: c.textPrimary,
    textSecondary: c.textSecondary,
    textMuted: c.textMuted,
    accent: c.accent,
    accentLight: c.accentLight,
    onAccent: c.onAccent,
    overlay: c.overlay,
    heroTagBg: c.heroTagBg,
    heroTagText: c.heroTagText,
    inputBg: c.inputBg,
    inputBorder: c.inputBorder,
    inputText: c.inputText,
    inputPlaceholder: c.inputPlaceholder,
    btnPrimaryBg: c.btnPrimaryBg,
    btnPrimaryText: c.btnPrimaryText,
    btnGhostBorder: c.btnGhostBorder,
    btnGhostText: c.btnGhostText,
    barTrack: c.barTrack,
    barFill: c.barFill,
    barPct: c.barPct,
    tabTrackBg: c.tabTrackBg,
    tabTrackBorder: c.tabTrackBorder,
    tabInactive: c.tabInactive,
    tabActiveText: c.tabActiveText,
    tagChipBg: c.tagChipBg,
    tagAffilBorder: c.tagAffilBorder,
    tagAffilText: c.tagAffilText,
    tagExpBorder: c.tagExpBorder,
    tagExpText: c.tagExpText,
    tagCharBorder: c.tagCharBorder,
    tagCharText: c.tagCharText,
    tagLikeBorder: c.tagLikeBorder,
    tagLikeText: c.tagLikeText,
    tagDislikeBorder: c.tagDislikeBorder,
    tagDislikeText: c.tagDislikeText,
    statBg: c.statBg,
    statBorder: c.statBorder,
    traitBg: c.traitBg,
    traitBorder: c.traitBorder,
    traitAccentLine: c.traitAccentLine,
    traitText: c.traitText,
    quoteText: c.quoteText,
    quoteDateText: c.quoteDateText,
    episodeBg: c.episodeBg,
    episodeBorder: c.episodeBorder,
    episodeTitle: c.episodeTitle,
    episodeDate: c.episodeDate,
    badgePrivateBg: c.badgePrivateBg,
    badgePrivateText: c.badgePrivateText,
    badgePublicBg: c.badgePublicBg,
    badgePublicText: c.badgePublicText,
    badgeLimitedBg: c.badgeLimitedBg,
    badgeLimitedText: c.badgeLimitedText,
    profileCardBorderWidth: 2,
    profileCardBorderColor: c.border,
    heroBackground: c.card,
    heroPhotoInitialBg: c.background,
    heroPhotoInitialBorder: c.border,
    heroPhotoInitialText: c.textSecondary,
    heroByTagText: c.textSecondary,
    tabPaneBackground: c.card,
    multiValueCardBackground: c.card,
    primaryButtonBg: c.accent,
    primaryButtonText: c.onAccent,
    modalOptionSelectedBg: c.accentLight,
    modalCloseButtonBg: c.border,
    roleToggleActiveBg: c.accentLight,
    roleToggleActiveText: c.accent,
    habitAddButtonBg: c.border,
    habitAddButtonBorder: c.border,
  },
  detailTabs: DETAIL_TABS,
  infoChipStyles: {
    所属: unifiedChip,
    経験: unifiedChip,
    性格: unifiedChip,
    好物: unifiedChip,
    苦手: unifiedChip,
  },
};
