import type { DetailDesignBundle, DetailTabDef } from './types';

const DETAIL_TABS: DetailTabDef[] = [
  { key: '情報', icon: 'book-outline', caption: 'info', color: '#4a7fd4' },
  { key: 'ステータス', icon: 'stats-chart-outline', caption: 'status', color: '#c9a227' },
  { key: 'エピソード', icon: 'film-outline', caption: 'episode', color: '#e07a2a' },
  { key: '習性', icon: 'cat', iconSet: 'material', caption: 'habit', color: '#3a9d5a' },
  { key: '彼曰く', icon: 'comment-account-outline', iconSet: 'material', caption: 'says', color: '#d44a4a' },
  { key: 'メモ', icon: 'notebook', iconSet: 'material', caption: 'note', color: '#8b5fd4' },
];

export const mainDetailDesign: DetailDesignBundle = {
  variant: 'main',
  label: 'メイン ver',
  tabMode: 'perTab',
  colors: {
    background: '#f2f5f8',
    card: '#ffffff',
    bgBase: '#f0f0f2',
    bgSurface: '#ffffff',
    bgElevated: '#f0f0f2',
    border: '#b8b8c4',
    textPrimary: '#333333',
    textSecondary: '#888888',
    textMuted: '#888888',
    accent: '#333333',
    accentLight: '#f0f0f2',
    onAccent: '#ffffff',
    overlay: 'rgba(51, 51, 51, 0.45)',
    heroTagBg: '#222222',
    heroTagText: '#f0f0f2',
    inputBg: '#ffffff',
    inputBorder: '#b8b8c4',
    inputText: '#333333',
    inputPlaceholder: '#888888',
    btnPrimaryBg: '#2d1f50',
    btnPrimaryText: '#c4b5fd',
    btnGhostBorder: '#b8b8c4',
    btnGhostText: '#888888',
    barTrack: '#d3d6dd',
    barFill: '#222222',
    barPct: '#333333',
    tabTrackBg: '#F8F8F8',
    tabTrackBorder: '#b8b8c4',
    tabInactive: '#888888',
    tabActiveText: '#ffffff',
    tagChipBg: 'transparent',
    tagAffilBorder: '#7c5cbf',
    tagAffilText: '#5c3a9f',
    tagExpBorder: '#2a9d5a',
    tagExpText: '#1a6b38',
    tagCharBorder: '#3a7abf',
    tagCharText: '#1a4a8a',
    tagLikeBorder: '#c49a00',
    tagLikeText: '#7a5f00',
    tagDislikeBorder: '#bf4a3a',
    tagDislikeText: '#8a1a1a',
    statBg: '#ffffff',
    statBorder: '#b8b8c4',
    traitBg: '#ffffff',
    traitBorder: '#b8b8c4',
    traitAccentLine: '#555555',
    traitText: '#333333',
    quoteText: '#333333',
    quoteDateText: '#888888',
    episodeBg: '#ffffff',
    episodeBorder: '#b8b8c4',
    episodeTitle: '#222222',
    episodeDate: '#888888',
    badgePrivateBg: 'transparent',
    badgePrivateText: '#666666',
    badgePublicBg: 'transparent',
    badgePublicText: '#1a6b38',
    badgeLimitedBg: 'transparent',
    badgeLimitedText: '#5c3a9f',
    profileCardBorderWidth: 4,
    profileCardBorderColor: '#aaaaaa',
    heroBackground: '#ffffff',
    heroPhotoInitialBg: '#1e1230',
    heroPhotoInitialBorder: 'rgba(167,139,250,0.2)',
    heroPhotoInitialText: '#c4b5fd',
    heroByTagText: '#c4b5fd',
    tabPaneBackground: '#f0f0f2',
    multiValueCardBackground: '#ffffff',
    primaryButtonBg: '#2d1f50',
    primaryButtonText: '#c4b5fd',
    modalOptionSelectedBg: '#e0f2fe',
    modalCloseButtonBg: '#e2e8f0',
    roleToggleActiveBg: '#2d1f50',
    roleToggleActiveText: '#c4b5fd',
    habitAddButtonBg: '#e2e8f0',
    habitAddButtonBorder: '#94a3b8',
  },
  detailTabs: DETAIL_TABS,
  infoChipStyles: {
    所属: { backgroundColor: 'transparent', borderColor: '#7c5cbf', color: '#5c3a9f', borderWidth: 1.5 },
    経験: { backgroundColor: 'transparent', borderColor: '#2a9d5a', color: '#1a6b38', borderWidth: 1.5 },
    性格: { backgroundColor: 'transparent', borderColor: '#3a7abf', color: '#1a4a8a', borderWidth: 1.5 },
    好物: { backgroundColor: 'transparent', borderColor: '#c49a00', color: '#7a5f00', borderWidth: 1.5 },
    苦手: { backgroundColor: 'transparent', borderColor: '#bf4a3a', color: '#8a1a1a', borderWidth: 1.5 },
    公開先: { backgroundColor: 'transparent', borderColor: '#b8b8c4', color: '#888888', borderWidth: 1.5 },
  },
};
